services:

  postgres:
    image: postgres:17
    container_name: satco-postgres
    restart: always

    environment:
      POSTGRES_USER: satco
      POSTGRES_PASSWORD: satco_password
      POSTGRES_DB: satco_platform

    ports:
      - "5432:5432"

    volumes:
      - ./postgres/data:/var/lib/postgresql/data


  backend:
    build:
      context: ./backend

    container_name: satco-backend
    restart: always

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: satco
      DATABASE_PASSWORD: satco_password
      DATABASE_NAME: satco_platform
      TEST_DATABASE_URL: postgresql+psycopg://satco:satco_password@postgres:5432/satco_platform_patch02022_test

    volumes:
      - ./backend:/app