"""ADR-025 repository and authorization ports."""

from typing import Protocol
from uuid import UUID


class EngineeringIdentifierAuthorization(Protocol):
    def authorize_object(self, *, actor_id: int, organization_id: UUID, object_id: UUID, mutate: bool) -> bool: ...


class EngineeringIdentifierRepository(Protocol):
    def get_object_locked(self, object_id: UUID, organization_id: UUID): ...
    def get_locked(self, identifier_id: UUID, organization_id: UUID): ...
    def get_object_id(self, identifier_id: UUID, organization_id: UUID): ...
    def current_set_locked(self, object_id: UUID, organization_id: UUID): ...
    def history(self, object_id: UUID, organization_id: UUID, *, limit: int, before): ...
    def add(self, value) -> None: ...
