from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.models.project import Project
from app.models.engineering_execution_plan import EngineeringExecutionActivity, EngineeringExecutionPlan
from app.schemas.engineering_execution_plan import ExecutionActor


class ExecutionPlanAuthorizationPort(Protocol):
    def get_project(self, *, actor: ExecutionActor, project_id: int, lock: bool = False) -> Project | None: ...
    def can_read(self, *, actor: ExecutionActor, project: Project) -> bool: ...
    def can_mutate(self, *, actor: ExecutionActor, project: Project) -> bool: ...
    def validate_workspace(self, *, actor: ExecutionActor, project: Project, workspace_id: int | None) -> bool: ...
    def validate_responsible_user(self, *, project: Project, user_id: int | None) -> bool: ...


class ProjectFoundationReadPort(Protocol):
    def is_established(self, *, actor: ExecutionActor, project_id: int) -> bool: ...


class ExecutionPlanRepositoryPort(Protocol):
    def get_plan(self, *, project_id: int, organization_id: UUID, lock: bool = False) -> EngineeringExecutionPlan | None: ...
    def get_activity(self, *, activity_id: UUID, plan_id: UUID, organization_id: UUID, lock: bool = False) -> EngineeringExecutionActivity | None: ...
    def add(self, item: object) -> None: ...
    def flush(self) -> None: ...


class ExecutionPlanUnitOfWorkPort(Protocol):
    repository: ExecutionPlanRepositoryPort
    def __enter__(self): ...
    def __exit__(self, exc_type, exc, traceback): ...
    def stage_audit(self, *, actor_id: int, project_id: int, operation: str, details: dict) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class ExecutionPlanClockPort(Protocol):
    def now(self) -> datetime: ...
