"""Inward-owned Evidence ports."""
from typing import Mapping, Protocol
from uuid import UUID
from app.models.evidence import Evidence
from app.models.evidence_command import EvidenceActor, EvidenceEvent, EvidenceOutcome, EvidenceResult
from app.models.supporting_file_command import SupportingFileHistoricalBasisV1

class EvidenceRepository(Protocol):
    def add(self, evidence: Evidence) -> None: ...
    def get_scoped(self, evidence_id: UUID, organization_id: UUID) -> Evidence | None: ...
    def list_scoped(self, *, organization_id: UUID, project_id: int, filters: Mapping, page: int, size: int) -> tuple[list[Evidence], int]: ...
    def persist_expected_version(self, evidence: Evidence, expected_version: int) -> bool: ...
    def get_scoped_for_update(self, evidence_id: UUID, organization_id: UUID) -> Evidence | None: ...
    def stage_supporting_file_links(self, *, evidence: Evidence, asset_ids: tuple[UUID, ...], actor_id: int, linked_at) -> None: ...
class EvidenceSupportingFileCollaborator(Protocol):
    def authorize_and_lock_for_evidence(self, *, actor_id: int, organization_id: UUID, project_id: int, workspace_id: int | None, asset_ids: tuple[UUID, ...]) -> tuple[SupportingFileHistoricalBasisV1, ...]: ...
class EvidenceAuthorizationPolicy(Protocol):
    def authorize(self, *, actor: EvidenceActor, operation: str, evidence: Evidence | None, project_id: int | None, workspace_id: int | None) -> bool: ...
class EvidenceValidator(Protocol):
    def validate_scope(self, *, actor: EvidenceActor, project_id: int | None, workspace_id: int | None) -> None: ...
    def validate_reference(self, *, actor: EvidenceActor, evidence_id: UUID, project_id: int, workspace_ids: tuple[int, ...]) -> Evidence: ...
class AuditRecorder(Protocol):
    def record(self, **values) -> None: ...
class DomainEventRecorder(Protocol):
    def record(self, events: tuple[EvidenceEvent, ...]) -> None: ...
class IdempotencyStore(Protocol):
    def find(self, **values) -> EvidenceOutcome | None: ...
    def reserve(self, **values) -> None: ...
    def record_result(self, result: EvidenceResult, authorized_state: Mapping) -> None: ...
class UnitOfWork(Protocol):
    evidence: EvidenceRepository; supporting_files: EvidenceSupportingFileCollaborator; audit: AuditRecorder; domain_events: DomainEventRecorder; idempotency: IdempotencyStore
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_value, traceback): ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
class Clock(Protocol):
    def now(self): ...
