"""Inward-owned Evidence ports."""
from typing import Mapping, Protocol
from uuid import UUID
from app.models.evidence import Evidence
from app.models.evidence_command import EvidenceActor, EvidenceEvent, EvidenceOutcome, EvidenceResult

class EvidenceRepository(Protocol):
    def add(self, evidence: Evidence) -> None: ...
    def get_scoped(self, evidence_id: UUID, organization_id: UUID) -> Evidence | None: ...
    def list_scoped(self, *, organization_id: UUID, project_id: int, filters: Mapping, page: int, size: int) -> tuple[list[Evidence], int]: ...
    def persist_expected_version(self, evidence: Evidence, expected_version: int) -> bool: ...
class EvidenceAuthorizationPolicy(Protocol):
    def authorize(self, *, actor: EvidenceActor, operation: str, evidence: Evidence | None, project_id: int | None, workspace_id: int | None) -> bool: ...
class EvidenceValidator(Protocol):
    def validate_scope(self, *, actor: EvidenceActor, project_id: int | None, workspace_id: int | None) -> None: ...
    def validate_reference(self, *, actor: EvidenceActor, evidence_id: UUID, project_id: int, workspace_ids: tuple[int, ...]) -> Evidence: ...
class AuditRecorder(Protocol):
    def record(self, **values) -> None: ...
class DomainEventRecorder(Protocol):
    def record(self, events: tuple[EvidenceEvent, ...]) -> None: ...
class IdempotencyStore(Protocol):
    def find(self, **values) -> EvidenceOutcome | None: ...
    def reserve(self, **values) -> None: ...
    def record_result(self, result: EvidenceResult, authorized_state: Mapping) -> None: ...
class UnitOfWork(Protocol):
    evidence: EvidenceRepository; audit: AuditRecorder; domain_events: DomainEventRecorder; idempotency: IdempotencyStore
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_value, traceback): ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
class Clock(Protocol):
    def now(self): ...
