from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.enums.project_foundation import ProjectInputSourceKind
from app.models.project import Project
from app.models.project_foundation import ProjectFoundation, ProjectRequiredInput
from app.schemas.project_foundation import ProjectFoundationActor, ProjectInputSourceCandidate, ProjectInputSafeSource


class ProjectFoundationRepositoryPort(Protocol):
    def get_project(self, project_id: int, organization_id: UUID, *, lock: bool = False) -> Project | None: ...
    def get_foundation(self, project_id: int, organization_id: UUID, *, lock: bool = False) -> ProjectFoundation | None: ...
    def get_input(self, input_id: UUID, project_id: int, organization_id: UUID, *, lock: bool = False) -> ProjectRequiredInput | None: ...
    def add(self, item: object) -> None: ...
    def load_children(self, project_id: int, organization_id: UUID) -> tuple[list, list, list]: ...
    def replace_basis_children(self, foundation: ProjectFoundation, *, in_scope: tuple[str, ...], out_of_scope: tuple[str, ...], completion_criteria: tuple[str, ...], actor_id: int, now: datetime) -> None: ...
    def reorder_inputs(self, project_id: int, organization_id: UUID, ordered_ids: tuple[UUID, ...], actor_id: int, now: datetime) -> bool: ...
    def flush(self) -> None: ...


class ProjectFoundationAuthorizationPort(Protocol):
    def can_read(self, *, actor: ProjectFoundationActor, project: Project) -> bool: ...
    def can_mutate(self, *, actor: ProjectFoundationActor, project: Project) -> bool: ...


class ProjectInputSourceAuthorizationPort(Protocol):
    def authorize_exact(self, *, actor: ProjectFoundationActor, project_id: int, kind: ProjectInputSourceKind, source_id: UUID, workspace_id: int | None) -> ProjectInputSafeSource: ...
    def list_authorized(self, *, actor: ProjectFoundationActor, project_id: int, kind: ProjectInputSourceKind, workspace_id: int | None, limit: int) -> tuple[ProjectInputSourceCandidate, ...]: ...


class ProjectFoundationClockPort(Protocol):
    def now(self) -> datetime: ...


class ProjectFoundationUnitOfWorkPort(Protocol):
    repository: ProjectFoundationRepositoryPort
    def __enter__(self): ...
    def __exit__(self, exc_type, exc, traceback): ...
    def stage_audit(self, *, actor_id: int, project_id: int, operation: str, details: dict) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
