"""Protocol-only owner read seams for PATCH-048 Batch 1."""

from __future__ import annotations

from typing import Protocol

from app.schemas.project_context import (
    ContextNodeSelector,
    EngineeringContextProjection,
    GraphDirection,
    OwnerPage,
    OwnerReadResult,
    ProjectContextActor,
    ProjectContextScope,
    SectionPageRequest,
    ContextRelationshipKind,
    GraphCandidatePage,
    GraphNodeReadResult,
)


class OwnerPrincipal(Protocol):
    """Trusted authenticated principal supplied by the existing auth boundary."""

    id: int


class EngineeringContextProjectContextReadPort(Protocol):
    def list_authorized_current(
        self,
        *,
        actor: ProjectContextActor,
        scope: ProjectContextScope,
        page: SectionPageRequest,
        current_user: OwnerPrincipal,
    ) -> OwnerPage | OwnerReadResult: ...
    def get_authorized_context(
        self,
        *,
        actor: ProjectContextActor,
        scope: ProjectContextScope,
        selector: ContextNodeSelector,
        current_user: OwnerPrincipal,
    ) -> OwnerReadResult: ...


class EngineeringContextRelationshipProjectContextReadPort(Protocol):
    def list_authorized_incident(
        self,
        *,
        actor: ProjectContextActor,
        scope: ProjectContextScope,
        selector: ContextNodeSelector,
        direction: GraphDirection,
        page: SectionPageRequest,
        current_user: OwnerPrincipal,
    ) -> OwnerPage | OwnerReadResult: ...


class ProjectContextOwnerReads(Protocol):
    """Fixed named owner calls; deliberately no source-name dispatch API."""
    def project_basis(self, *, actor: ProjectContextActor, scope: ProjectContextScope, page: SectionPageRequest, current_user: OwnerPrincipal) -> OwnerReadResult: ...
    def execution(self, *, actor: ProjectContextActor, scope: ProjectContextScope, page: SectionPageRequest, current_user: OwnerPrincipal) -> OwnerReadResult: ...
    def deliverables(self, *, actor: ProjectContextActor, scope: ProjectContextScope, page: SectionPageRequest, current_user: OwnerPrincipal) -> OwnerReadResult: ...
    def project_control(self, *, control_kind: str, actor: ProjectContextActor, scope: ProjectContextScope, page: SectionPageRequest, current_user: OwnerPrincipal) -> OwnerReadResult: ...
    def engineering_context(self, *, actor: ProjectContextActor, scope: ProjectContextScope, page: SectionPageRequest, current_user: OwnerPrincipal) -> OwnerReadResult: ...
    def engineering_objects(self, *, actor: ProjectContextActor, scope: ProjectContextScope, page: SectionPageRequest, current_user: OwnerPrincipal) -> OwnerReadResult: ...
    def evidence(self, *, actor: ProjectContextActor, scope: ProjectContextScope, page: SectionPageRequest, current_user: OwnerPrincipal) -> OwnerReadResult: ...
    def supporting_files(self, *, actor: ProjectContextActor, scope: ProjectContextScope, page: SectionPageRequest, current_user: OwnerPrincipal) -> OwnerReadResult: ...
    def technical_reports(self, *, actor: ProjectContextActor, scope: ProjectContextScope, page: SectionPageRequest, current_user: OwnerPrincipal) -> OwnerReadResult: ...
    def organizational_memory(self, *, actor: ProjectContextActor, scope: ProjectContextScope, page: SectionPageRequest, current_user: OwnerPrincipal) -> OwnerReadResult: ...


class ProjectContextGraphReads(Protocol):
    """Closed named graph-owner seam.  Deliberately no generic resolver."""
    def project_node(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, current_user: OwnerPrincipal) -> GraphNodeReadResult: ...
    def workspace_node(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, current_user: OwnerPrincipal) -> GraphNodeReadResult: ...
    def execution_plan_node(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, current_user: OwnerPrincipal) -> GraphNodeReadResult: ...
    def activity_node(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, current_user: OwnerPrincipal) -> GraphNodeReadResult: ...
    def milestone_node(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, current_user: OwnerPrincipal) -> GraphNodeReadResult: ...
    def deliverable_node(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, current_user: OwnerPrincipal) -> GraphNodeReadResult: ...
    def deliverable_revision_node(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, current_user: OwnerPrincipal) -> GraphNodeReadResult: ...
    def risk_node(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, current_user: OwnerPrincipal) -> GraphNodeReadResult: ...
    def issue_node(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, current_user: OwnerPrincipal) -> GraphNodeReadResult: ...
    def decision_node(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, current_user: OwnerPrincipal) -> GraphNodeReadResult: ...
    def change_node(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, current_user: OwnerPrincipal) -> GraphNodeReadResult: ...
    def change_impact_node(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, current_user: OwnerPrincipal) -> GraphNodeReadResult: ...
    def engineering_object_node(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, current_user: OwnerPrincipal) -> GraphNodeReadResult: ...
    def engineering_context_node(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, current_user: OwnerPrincipal) -> GraphNodeReadResult: ...
    def evidence_node(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, current_user: OwnerPrincipal) -> GraphNodeReadResult: ...
    def supporting_file_node(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, current_user: OwnerPrincipal) -> GraphNodeReadResult: ...
    def technical_report_node(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, current_user: OwnerPrincipal) -> GraphNodeReadResult: ...
    def organizational_memory_node(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, current_user: OwnerPrincipal) -> GraphNodeReadResult: ...
    def engineering_relationship_edges(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, direction: GraphDirection, page: SectionPageRequest, current_user: OwnerPrincipal) -> GraphCandidatePage | OwnerReadResult: ...
    def context_relationship_edges(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, direction: GraphDirection, page: SectionPageRequest, current_user: OwnerPrincipal) -> GraphCandidatePage | OwnerReadResult: ...
    def execution_edges(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, direction: GraphDirection, page: SectionPageRequest, current_user: OwnerPrincipal) -> GraphCandidatePage | OwnerReadResult: ...
    def deliverable_edges(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, direction: GraphDirection, page: SectionPageRequest, current_user: OwnerPrincipal) -> GraphCandidatePage | OwnerReadResult: ...
    def project_control_edges(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, direction: GraphDirection, page: SectionPageRequest, current_user: OwnerPrincipal) -> GraphCandidatePage | OwnerReadResult: ...
    def evidence_file_edges(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, direction: GraphDirection, page: SectionPageRequest, current_user: OwnerPrincipal) -> GraphCandidatePage | OwnerReadResult: ...
    def technical_report_edges(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, direction: GraphDirection, page: SectionPageRequest, current_user: OwnerPrincipal) -> GraphCandidatePage | OwnerReadResult: ...
    def organizational_memory_edges(self, *, actor: ProjectContextActor, scope: ProjectContextScope, selector: ContextNodeSelector, direction: GraphDirection, page: SectionPageRequest, current_user: OwnerPrincipal) -> GraphCandidatePage | OwnerReadResult: ...
