"""Inward-owned PATCH-055 retention governance ports."""
from typing import Protocol
from uuid import UUID

from app.models.retention_command import RetentionSubject


class RetentionRepositoryPort(Protocol):
    def resolve_subject(self, *, organization_id: UUID, subject_kind: str, subject_id: UUID, lock: bool = False): ...
    def get_current_record(self, *, subject: RetentionSubject, lock: bool = False): ...
    def get_record_by_id(self, *, subject: RetentionSubject, record_id: UUID): ...
    def get_active_hold(self, *, subject: RetentionSubject, lock: bool = False): ...
    def get_hold_revision(
        self,
        *,
        subject: RetentionSubject,
        hold_id: UUID,
        version: int,
    ): ...
    def get_latest_hold(self, *, subject: RetentionSubject): ...
    def get_latest_decision(self, *, retention_record_id: UUID): ...
    def get_decision_by_request_digest(self, *, retention_record_id: UUID, request_digest: str): ...
    def close_current_record(self, *, record_id: UUID, expected_version: int) -> bool: ...
    def close_hold_revision(self, *, row_id: UUID, expected_version: int) -> bool: ...
    def add(self, row) -> None: ...
    def flush(self) -> None: ...


class RetentionAuthorizationPort(Protocol):
    def authorize_actor(self, *, actor_id: int, organization_id: UUID) -> bool: ...
    def authorize_read(self, *, actor_id: int, subject: RetentionSubject) -> bool: ...
    def authorize_mutation(self, *, actor_id: int, subject: RetentionSubject) -> bool: ...


class RetentionIdempotencyPort(Protocol):
    def get(self, *, organization_id: UUID, actor_id: int, operation: str, idempotency_key: UUID, lock: bool = False): ...
    def reserve(self, **values): ...
    def complete(self, row, *, safe_result: dict, completed_at): ...


class RetentionAuditPort(Protocol):
    def record(self, **values) -> None: ...


class RetentionOutboxPort(Protocol):
    def record(self, **values) -> None: ...


class RetentionUnitOfWorkPort(Protocol):
    retention: RetentionRepositoryPort
    authorization: RetentionAuthorizationPort
    idempotency: RetentionIdempotencyPort
    audit: RetentionAuditPort
    outbox: RetentionOutboxPort

    def __enter__(self): ...
    def __exit__(self, exc_type, exc_value, traceback): ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class RetentionExportStore(Protocol):
    """Private immutable export-artifact store; locator details stay inward-only."""
    def put_private(self, *, export_id: UUID, stream, media_type: str): ...
    def head_exact(self, *, export_id: UUID, version: str): ...
    def open_exact(self, *, export_id: UUID, version: str): ...


class RetentionRecoveryResolver(Protocol):
    """One-subject exact-byte resolver; authorization remains service-owned."""
    def resolve_authorized(
        self,
        *,
        subject: RetentionSubject,
        expected_digest: str | None,
    ): ...


class Clock(Protocol):
    def now(self): ...
