"""Narrow ports for the Batch-1 standards aggregate."""

from __future__ import annotations

from typing import Protocol
from uuid import UUID


class StandardsRepositoryPort(Protocol):
    def get_identity(self, identity_id: UUID, organization_id: UUID | None = None): ...
    def get_edition(self, edition_id: UUID): ...
    def get_current_rights(self, organization_id: UUID, edition_id: UUID, provider_id: str, *, lock: bool = False): ...
    def snapshot(self, snapshot_id: UUID, organization_id: UUID, project_id: int): ...
    def assertion(self, assertion_id: UUID, organization_id: UUID, project_id: int): ...
    def resolve_provider_handle(self, snapshot_id: UUID, organization_id: UUID, actor_id: int, purpose: str): ...
    def current_applicability(self, organization_id: UUID, project_id: int, edition_id: UUID, *, lock: bool = False): ...
    def applicability(self, applicability_id: UUID, organization_id: UUID, project_id: int, *, lock: bool = False): ...


class StandardsPackageCandidatePort(Protocol):
    def candidates(self, *, organization_id: UUID, project_id: int, package_version: str | None = None) -> list[dict]: ...


class StandardSourceObjectStorePort(Protocol):
    def put_private(self, *, organization_id: UUID, project_id: int, snapshot_id: UUID, content: bytes, media_type: str): ...
    def head_exact(self, key: str, version: str): ...
    def open_exact(self, key: str, version: str): ...
    def delete_exact(self, key: str, version: str) -> None: ...


class StandardsUnitOfWorkPort(Protocol):
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
