import { useEffect, useMemo, useState, type FormEvent } from "react";
import { CheckCircle2, ClipboardList, Flag, Plus, RefreshCw } from "lucide-react";
import { api } from "../api/client";
import type { ApiResult, ExecutionActivity, ExecutionActivityStanding, ExecutionPlan, Project, Workspace } from "../api/types";
import { EmptyState, ErrorState, LoadingState, ProtectedState, StatusBadge } from "./States";
import { Surface } from "./Page";

const standingOptions: ExecutionActivityStanding[] = ["planned", "ready", "in_progress", "blocked", "completed", "cancelled"];

function Message({ result }: { result: ApiResult<unknown> | null }) {
  if (!result || result.state === "success") return null;
  const text = result.state === "protected" ? "This operation is not available." : result.state === "invalid" ? "Check the supplied engineering execution details." : result.state === "conflict" ? "The execution plan changed. Reload and try again." : "The execution plan service is unavailable.";
  return <p className="form-message" role="alert">{text}</p>;
}

export function EngineeringExecutionPlanPanel({ projectId, project, workspaces }: { projectId: number; project: Project; workspaces: Workspace[] }) {
  const [plan, setPlan] = useState<ApiResult<ExecutionPlan> | null>(null);
  const [result, setResult] = useState<ApiResult<unknown> | null>(null);
  const [busy, setBusy] = useState(false);
  const [title, setTitle] = useState(""); const [basis, setBasis] = useState(""); const [rationale, setRationale] = useState("");
  const [workspaceId, setWorkspaceId] = useState(""); const [responsibleId, setResponsibleId] = useState(""); const [targetDate, setTargetDate] = useState("");
  const [transitionTarget, setTransitionTarget] = useState<Record<string, ExecutionActivityStanding>>({});
  const [dependencySource, setDependencySource] = useState(""); const [dependencyTarget, setDependencyTarget] = useState("");
  const [milestoneTitle, setMilestoneTitle] = useState(""); const [milestoneBasis, setMilestoneBasis] = useState(""); const [milestoneActivityIds, setMilestoneActivityIds] = useState<string[]>([]);
  const load = () => { setPlan(null); void api.executionPlan(projectId).then(setPlan); };
  useEffect(load, [projectId]);
  const current = plan?.state === "success" && plan.data.availability === "established" ? plan.data : null;
  const people = useMemo(() => [project.owner, project.primary_assignee].filter((person, index, all) => person && all.findIndex((candidate) => candidate?.id === person.id) === index), [project]);
  async function execute(action: () => Promise<ApiResult<unknown>>) { setBusy(true); setResult(null); const next = await action(); setResult(next); setBusy(false); if (next.state === "success") load(); }
  function establish(event: FormEvent) { event.preventDefault(); void execute(() => api.establishExecutionPlan(projectId, { expected_plan_version: 0, rationale })); }
  function createActivity(event: FormEvent) { event.preventDefault(); if (!current) return; void execute(() => api.createExecutionActivity(projectId, { expected_plan_version: current.version, title, description: null, ordinal: current.activities.length, workspace_id: workspaceId ? Number(workspaceId) : null, responsible_user_id: responsibleId ? Number(responsibleId) : null, target_date: targetDate || null, completion_basis: basis, rationale })); }
  function transition(activity: ExecutionActivity) { const target = transitionTarget[activity.id] ?? "ready"; void execute(() => api.transitionExecutionActivity(projectId, activity.id, { expected_activity_version: activity.version, target_standing: target, rationale })); }
  function addDependency(event: FormEvent) { event.preventDefault(); if (!current || !dependencySource || !dependencyTarget || dependencySource === dependencyTarget) return; const dependencies = [...current.dependencies, { predecessor_activity_id: dependencySource, dependent_activity_id: dependencyTarget }]; void execute(() => api.replaceExecutionDependencies(projectId, { expected_plan_version: current.version, dependencies, rationale })); }
  function addMilestone(event: FormEvent) { event.preventDefault(); if (!current) return; void execute(() => api.createExecutionMilestone(projectId, { expected_plan_version: current.version, title: milestoneTitle, completion_basis: milestoneBasis, target_date: null, ordinal: current.milestones.length, activity_ids: milestoneActivityIds, rationale })); }
  const toggleMilestoneActivity = (id: string) => setMilestoneActivityIds((items) => items.includes(id) ? items.filter((value) => value !== id) : [...items, id]);
  return <section className="execution-plan" aria-labelledby="execution-plan-title"><div className="execution-plan-heading"><div><span className="eyebrow">Governed engineering execution</span><h2 id="execution-plan-title">Execution plan, activities and milestones</h2><p>Human-governed engineering work. Progress is derived only from current activity standings and does not replace Project completion.</p></div><button type="button" className="button secondary compact" onClick={load}><RefreshCw size={15} />Reload</button></div>
    {!plan ? <LoadingState /> : plan.state === "protected" || plan.state === "invalid" ? <ProtectedState /> : plan.state !== "success" ? <ErrorState unavailable={plan.state === "unavailable"} /> : plan.data.availability === "plan_not_established" ? <Surface title="Engineering execution is not established" subtitle="Legacy Project data remains unchanged"><form className="execution-form" onSubmit={establish}><label>Human rationale<textarea value={rationale} onChange={(event) => setRationale(event.target.value)} rows={2} maxLength={2000} required /></label><button className="button primary" disabled={busy || !plan.data.allowed_actions.includes("establish")}><ClipboardList size={15} />Establish execution plan</button></form></Surface> : current ? <>
      <div className="execution-summary"><Surface><span className="eyebrow">Derived progress</span><strong className="hero-metric">{current.progress.percent}%</strong><small>{current.progress.completed_count} completed of {current.progress.eligible_count} eligible activities</small></Surface><Surface><span className="eyebrow">Milestones</span><strong className="hero-metric">{current.milestones.length}</strong><small>Derived from activity completion; never a generic task list.</small></Surface></div>
      <div className="execution-grid"><Surface title="Activities" subtitle="Current canonical engineering execution facts"><div className="execution-activity-list">{current.activities.length ? current.activities.map((activity) => <article key={activity.id}><div><strong>{activity.title}</strong><span>{activity.completion_basis} · Version {activity.version}{activity.target_date ? ` · Target ${activity.target_date}` : ""}</span>{activity.blocker_rationale ? <small>Blocked: {activity.blocker_rationale}</small> : null}</div><StatusBadge value={activity.standing} /><div className="execution-transition"><select aria-label={`Target standing for ${activity.title}`} value={transitionTarget[activity.id] ?? "ready"} onChange={(event) => setTransitionTarget({ ...transitionTarget, [activity.id]: event.target.value as ExecutionActivityStanding })}>{standingOptions.map((standing) => <option key={standing} value={standing}>{standing.replaceAll("_", " ")}</option>)}</select><button type="button" className="button secondary compact" disabled={busy || !rationale.trim()} onClick={() => transition(activity)}>Update standing</button></div></article>) : <EmptyState title="No activities yet" detail="Create the first bounded engineering activity from the accepted Project foundation." />}</div></Surface><Surface title="Add activity" subtitle="Human-defined engineering work"><form className="execution-form" onSubmit={createActivity}><label>Activity title<input value={title} onChange={(event) => setTitle(event.target.value)} maxLength={200} required /></label><label>Completion basis<textarea value={basis} onChange={(event) => setBasis(event.target.value)} rows={3} maxLength={2000} required /></label><label>Engineering Workspace <select value={workspaceId} onChange={(event) => setWorkspaceId(event.target.value)}><option value="">Project-level / no Workspace</option>{workspaces.map((workspace) => <option key={workspace.id} value={workspace.id}>{workspace.display_name}</option>)}</select></label><label>Responsible engineer <select value={responsibleId} onChange={(event) => setResponsibleId(event.target.value)}><option value="">Unassigned</option>{people.map((person) => person ? <option key={person.id} value={person.id}>{person.full_name || person.username}</option> : null)}</select></label><label>Target date <input type="date" value={targetDate} onChange={(event) => setTargetDate(event.target.value)} /></label><label>Human rationale<textarea value={rationale} onChange={(event) => setRationale(event.target.value)} rows={2} maxLength={2000} required /></label><button className="button primary" disabled={busy}><Plus size={15} />Add activity</button></form></Surface></div>
      <div className="execution-grid execution-supporting"><Surface title="Dependencies" subtitle="Bounded sequencing, not a workflow engine"><form className="execution-form" onSubmit={addDependency}><label>Predecessor activity <select value={dependencySource} onChange={(event) => setDependencySource(event.target.value)} required><option value="">Select activity</option>{current.activities.map((activity) => <option key={activity.id} value={activity.id}>{activity.title}</option>)}</select></label><label>Dependent activity <select value={dependencyTarget} onChange={(event) => setDependencyTarget(event.target.value)} required><option value="">Select activity</option>{current.activities.map((activity) => <option key={activity.id} value={activity.id}>{activity.title}</option>)}</select></label><button className="button secondary" disabled={busy || !rationale.trim()}>Add dependency</button></form>{current.dependencies.length ? <ul className="execution-links">{current.dependencies.map((edge) => <li key={`${edge.predecessor_activity_id}-${edge.dependent_activity_id}`}>{current.activities.find((activity) => activity.id === edge.predecessor_activity_id)?.title} → {current.activities.find((activity) => activity.id === edge.dependent_activity_id)?.title}</li>)}</ul> : <p className="form-hint">No dependencies defined.</p>}</Surface><Surface title="Milestones" subtitle="Derived from linked activity completion"><form className="execution-form" onSubmit={addMilestone}><label>Milestone title<input value={milestoneTitle} onChange={(event) => setMilestoneTitle(event.target.value)} maxLength={200} required /></label><label>Completion basis<textarea value={milestoneBasis} onChange={(event) => setMilestoneBasis(event.target.value)} rows={2} maxLength={2000} required /></label><fieldset><legend>Linked activities</legend>{current.activities.map((activity) => <label className="check-row" key={activity.id}><input type="checkbox" checked={milestoneActivityIds.includes(activity.id)} onChange={() => toggleMilestoneActivity(activity.id)} />{activity.title}</label>)}</fieldset><button className="button secondary" disabled={busy || !rationale.trim()}><Flag size={15} />Add milestone</button></form>{current.milestones.length ? <ul className="execution-links">{current.milestones.map((milestone) => <li key={milestone.id}><CheckCircle2 size={14} />{milestone.title} · {milestone.standing.replaceAll("_", " ")}</li>)}</ul> : <p className="form-hint">No milestones defined.</p>}</Surface></div>
      <Message result={result} />
    </> : null}
  </section>;
}
