import { useEffect, useState, type FormEvent } from "react";
import { FileStack, Plus, RefreshCw } from "lucide-react";
import { api } from "../api/client";
import type { ApiResult, Deliverable, DeliverableRegister } from "../api/types";
import { EmptyState, ErrorState, LoadingState, ProtectedState, StatusBadge } from "./States";
import { Surface } from "./Page";

export function EngineeringDeliverableRegisterPanel({ projectId }: { projectId:number }) {
  const [register,setRegister]=useState<ApiResult<DeliverableRegister>|null>(null); const [result,setResult]=useState<ApiResult<unknown>|null>(null); const [busy,setBusy]=useState(false);
  const [code,setCode]=useState("");const [title,setTitle]=useState("");const [discipline,setDiscipline]=useState("electrical");const [kind,setKind]=useState("drawing");const [authority,setAuthority]=useState<Deliverable["external_authority"]>("cad");const [label,setLabel]=useState("");const [rationale,setRationale]=useState("");
  const load=()=>{setRegister(null);void api.deliverables(projectId).then(setRegister)}; useEffect(load,[projectId]);
  async function create(event:FormEvent){event.preventDefault();setBusy(true);setResult(await api.createDeliverable(projectId,{code,title,discipline,deliverable_type:kind,purpose:null,external_authority:authority,workspace_id:null,activity_id:null,milestone_id:null,responsible_user_id:null,target_date:null,initial_external_label:label,rationale}));setBusy(false);load()}
  if(!register)return <LoadingState/>; if(register.state==="protected"||register.state==="invalid")return <ProtectedState/>;if(register.state!=="success")return <ErrorState unavailable={register.state==="unavailable"}/>;
  return <section className="execution-plan" aria-labelledby="deliverable-register-title"><div className="execution-plan-heading"><div><span className="eyebrow">Governed external-tool document control</span><h2 id="deliverable-register-title">Engineering Deliverable Register</h2><p>Control identity and revision facts only. Professional authoring tools remain authoritative for authored content.</p></div><button type="button" className="button secondary compact" onClick={load}><RefreshCw size={15}/>Reload</button></div><div className="execution-grid"><Surface title="Current deliverables" subtitle="Authorized Project control facts">{register.data.items.length?<div className="execution-activity-list">{register.data.items.map(item=><article key={item.id}><div><strong>{item.code} · {item.title}</strong><span>{item.discipline} · {item.deliverable_type} · External authority: {item.external_authority}</span><small>Current revision: {item.current_revision.external_label} · Sequence {item.current_revision.sequence}</small></div><StatusBadge value={item.standing}/></article>)}</div>:<EmptyState title="No deliverables are registered" detail="Register the first external-tool engineering work product when it exists."/>}</Surface><Surface title="Register deliverable" subtitle="No authored content or private file identity is entered here"><form className="execution-form" onSubmit={create}><label>Deliverable code<input value={code} onChange={e=>setCode(e.target.value)} maxLength={64} required/></label><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={200} required/></label><label>Discipline<input value={discipline} onChange={e=>setDiscipline(e.target.value)} maxLength={80} required/></label><label>Type<input value={kind} onChange={e=>setKind(e.target.value)} maxLength={80} required/></label><label>External authoring authority<select value={authority} onChange={e=>setAuthority(e.target.value as Deliverable["external_authority"])}>{["cad","eplan","etap","spreadsheet","document","vendor_tool","other"].map(v=><option key={v}>{v}</option>)}</select></label><label>External revision label<input value={label} onChange={e=>setLabel(e.target.value)} maxLength={80} required/></label><label>Human rationale<textarea value={rationale} onChange={e=>setRationale(e.target.value)} maxLength={2000} rows={2} required/></label><button className="button primary" disabled={busy}><Plus size={15}/>Register deliverable</button>{result&&result.state!=="success"?<p className="form-message" role="alert">{result.state==="invalid"?"Check the supplied deliverable control facts.":"This operation is not available."}</p>:null}</form></Surface></div></section>
}
