import { useEffect, useState } from "react";
import { api } from "../api/client";
import type { ApiResult, EvidenceRecord } from "../api/types";
import { ErrorState, LoadingState, ProtectedState, StatusBadge } from "./States";
import { Surface } from "./Page";
import { EvidenceLineageReliancePanel } from "./EvidenceLineageReliancePanel";
import { RetentionGovernancePanel } from "./RetentionGovernancePanel";
import { RetentionExportRecoveryPanel } from "./RetentionExportRecoveryPanel";
import { retentionApi } from "../services/retentionApi";
import type { EvidenceWorkbenchState } from "../services/retentionApi";
export function EvidenceWorkbench({projectId,workspaceId}:{projectId:number;workspaceId:number}){
 const [evidence,setEvidence]=useState<ApiResult<{items:EvidenceRecord[]}>|null>(null);const [workbench,setWorkbench]=useState<ApiResult<EvidenceWorkbenchState>|null>(null);const [selected,setSelected]=useState("");const [rationale,setRationale]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [fact,setFact]=useState("");const [sourceRef,setSourceRef]=useState("");const [replacement,setReplacement]=useState("");
 const load=()=>{setEvidence(null);setWorkbench(null);void api.evidence(projectId,workspaceId).then(setEvidence);void retentionApi.workbench(projectId,workspaceId).then(setWorkbench);};useEffect(()=>{setSelected("");setRationale("");setMessage("");load();},[projectId,workspaceId]);
 const items=evidence?.state==="success"?evidence.data.items:[];const current=items.find(x=>x.id===selected);
 async function createEvidence(){if(!fact.trim()||!sourceRef.trim()||!rationale.trim())return;setBusy(true);const result=await retentionApi.createEvidence({project_id:projectId,workspace_id:workspaceId,source_kind:"engineering_record",source_reference:sourceRef.trim(),source_revision:"current",source_standing:"current",effective_at:null,supported_fact:fact.trim(),rationale:rationale.trim()});setMessage(result.state==="success"?"Proposed Evidence created. It remains non-authoritative until explicit Human acceptance.":result.state==="protected"?"Evidence creation is not available in the current authorized scope.":"Proposed Evidence was not created.");if(result.state==="success"){setFact("");setSourceRef("");setRationale("");load();}setBusy(false);}
 async function transition(lifecycle:"current"|"withdrawn"|"superseded"){if(!current||!rationale.trim())return;setBusy(true);const result=await retentionApi.evidenceTransition(current.id,current.version,lifecycle,rationale.trim(),lifecycle==="superseded"?replacement:null);setMessage(result.state==="success"?"Human Evidence lifecycle decision recorded; authoritative state reread.":result.state==="conflict"?"Evidence changed. Reread required before another Human decision.":"Lifecycle action could not be completed.");setBusy(false);load();}
 return <section aria-labelledby="evidence-workbench-title"><h2 id="evidence-workbench-title">Evidence Workbench</h2><p>Scanner availability, Evidence currentness, historical reliance and retention eligibility are separate governed states.</p>{!evidence?<LoadingState/>:evidence.state==="protected"?<ProtectedState/>:evidence.state!=="success"?<ErrorState unavailable={evidence.state==="unavailable"}/>:<><Surface title="Create proposed Evidence" subtitle="Human-authored proposal · not authoritative until accepted"><label>Supported engineering fact<textarea rows={2} maxLength={2000} value={fact} onChange={e=>setFact(e.target.value)}/></label><label>Source reference<input value={sourceRef} maxLength={512} onChange={e=>setSourceRef(e.target.value)}/></label><label>Creation rationale<textarea rows={2} value={rationale} onChange={e=>setRationale(e.target.value)}/></label><button type="button" className="button secondary" disabled={busy||!fact.trim()||!sourceRef.trim()||!rationale.trim()} onClick={()=>void createEvidence()}>Create proposed Evidence</button></Surface><Surface title="Human Evidence lifecycle" subtitle="Acceptance remains an explicit Human authority action"><label>Evidence<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select visible Evidence</option>{items.map(x=><option key={x.id} value={x.id}>{x.supported_fact}</option>)}</select></label>{current?<p><StatusBadge value={current.lifecycle}/> · Version {current.version}</p>:null}<label>Human rationale<textarea rows={2} maxLength={2000} value={rationale} onChange={e=>setRationale(e.target.value)}/></label><label>Replacement Evidence<select value={replacement} onChange={e=>setReplacement(e.target.value)}><option value="">Select authorized current replacement</option>{items.filter(x=>x.lifecycle==="current"&&x.id!==current?.id).map(x=><option key={x.id} value={x.id}>{x.supported_fact}</option>)}</select></label><div className="record-actions"><button type="button" className="button primary" disabled={busy||current?.lifecycle!=="proposed"||!rationale.trim()} onClick={()=>void transition("current")}>Accept as current Evidence</button><button type="button" className="button secondary" disabled={busy||!current||!["proposed","current"].includes(current.lifecycle)||!rationale.trim()} onClick={()=>void transition("withdrawn")}>Withdraw Evidence</button><button type="button" className="button secondary" disabled={busy||current?.lifecycle!=="current"||!replacement||!rationale.trim()} onClick={()=>void transition("superseded")}>Supersede with selected Evidence</button></div><p aria-live="polite" role="status">{message}</p></Surface><EvidenceLineageReliancePanel evidence={items} workbench={workbench?.state==="success"?workbench.data:null}/><RetentionGovernancePanel evidence={items} projectId={projectId} workspaceId={workspaceId}/><RetentionExportRecoveryPanel evidence={items} projectId={projectId} workspaceId={workspaceId}/></>}</section>;
}
