import { useEffect, useState } from "react";
import { api } from "../api/client";
import type { ApiResult, CommercialEntitlementStatus, OrganizationPackageConfiguration, SupportedPackages } from "../api/types";

export function OrganizationPackageConfigurationPanel() {
  const [configuration,setConfiguration]=useState<ApiResult<OrganizationPackageConfiguration>|null>(null);
  const [supported,setSupported]=useState<ApiResult<SupportedPackages>|null>(null);
  const [commercial,setCommercial]=useState<ApiResult<CommercialEntitlementStatus>|null>(null);
  const [rationale,setRationale]=useState(""); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  const load=()=>{if(typeof api.organizationPackageConfiguration==="function") void api.organizationPackageConfiguration().then(setConfiguration);if(typeof api.supportedPackages==="function") void api.supportedPackages().then(setSupported);if(typeof api.commercialEntitlement==="function") void api.commercialEntitlement().then(setCommercial)};
  useEffect(load,[]);
  if(configuration?.state!=="success"||supported?.state!=="success"||!Array.isArray(configuration.data.enabled_selections)||!Array.isArray(supported.data.items)) return <section className="surface"><h2>Package configuration</h2><p className="form-hint">Package configuration is unavailable or not disclosed.</p></section>;
  const commercialStatus=commercial?.state==="success"&&typeof commercial.data.available==="boolean"&&Array.isArray(commercial.data.package_keys)?commercial.data:null;
  const commercialBlocked=commercialStatus ? !commercialStatus.available : false;
  const enabled=new Set(configuration.data.enabled_selections.map(item=>`${item.package_key}@${item.package_version}`));
  const toggle=(key:string)=>{ if(enabled.has(key)) enabled.delete(key); else enabled.add(key); setConfiguration({state:"success",data:{...configuration.data,enabled_selections:supported.data.items.filter(item=>enabled.has(`${item.package_key}@${item.package_version}`)).map(item=>({package_key:item.package_key,package_version:item.package_version}))}}); };
  const save=async()=>{setBusy(true);const result=await api.replaceOrganizationPackageConfiguration({expected_configuration_version:configuration.data.configuration_version,enabled_selections:configuration.data.enabled_selections,rationale});if(result.state==="success"){setRationale("");setMessage("Package configuration was accepted by the server.");load()}else setMessage(result.state==="conflict"?"The server denied this package configuration against current entitlement or configuration state.":result.state==="protected"?"Package configuration is not available in the current authorized context.":"The server did not accept this package configuration.");setBusy(false)};
  return <section className="surface package-panel"><h2>Discipline package configuration</h2><p>Configuration is not commercial entitlement and never grants engineering authority.</p>{commercialStatus?<p className="form-hint">Server commercial status: {commercialStatus.effective_state.replaceAll("_"," ").toUpperCase()}. Only server-returned entitled packages are enabled here for usability; the backend re-evaluates every save.</p>:<p className="form-hint">Commercial package status is unavailable or not disclosed. The backend remains authoritative.</p>}<div className="package-list">{supported.data.items.map(item=>{const key=`${item.package_key}@${item.package_version}`;const notEntitled=commercialStatus?!commercialStatus.package_keys.some(packageKey=>packageKey===item.package_key):false;return <label key={key}><input type="checkbox" checked={enabled.has(key)} disabled={commercialBlocked||notEntitled} onChange={()=>toggle(key)} />{item.package_key} <small>{item.package_version}{notEntitled?" · not entitled by server":""}</small></label>})}</div><label>Rationale<textarea value={rationale} onChange={e=>setRationale(e.target.value)} maxLength={2000} /></label><button className="button secondary" disabled={busy||commercialBlocked||!rationale.trim()} onClick={()=>void save()}>Save package configuration</button>{message?<p className="form-message" role="status">{message}</p>:null}</section>;
}
