import { useEffect, useState } from "react";
import type { EvidenceRecord } from "../api/types";
import { retentionApi, type RetentionExport, type RetentionRecovery, type RetentionSubject } from "../services/retentionApi";
import { StatusBadge } from "./States";
import { Surface } from "./Page";
export function RetentionExportRecoveryPanel({evidence,projectId,workspaceId}:{evidence:EvidenceRecord[];projectId:number;workspaceId:number}){
 const [selected,setSelected]=useState("");const [purpose,setPurpose]=useState("");const [exp,setExp]=useState<RetentionExport|null>(null);const [rec,setRec]=useState<RetentionRecovery|null>(null);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{setSelected("");setPurpose("");setExp(null);setRec(null);setMessage("");},[projectId,workspaceId]);
 const item=evidence.find(x=>x.id===selected);const subject:RetentionSubject|undefined=item?{subject_kind:"evidence",subject_id:item.id,organization_id:item.organization_id,project_id:projectId,workspace_id:workspaceId}:undefined;
 async function createExport(){if(!subject||!item||!purpose.trim())return;setBusy(true);const r=await retentionApi.export([{subject,subject_version:item.version}],purpose.trim());if(r.state==="success"){setExp(r.data);setMessage("Governed export requested. Status remains server-authoritative.");}else setMessage(r.state==="conflict"?"Export state changed; reread before resubmission.":"Export is unavailable in the current authorized scope.");setBusy(false);}
 async function recover(){if(!subject)return;setBusy(true);const r=await retentionApi.recovery(subject);if(r.state==="success"){setRec(r.data);setMessage("Recovery status recorded. Recovery does not revive withdrawn or superseded Evidence.");}else setMessage("Recovery could not establish protected content availability.");setBusy(false);}
 return <Surface title="Governed export & recovery" subtitle="No raw locator or storage key is exposed"><label>Evidence<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select visible Evidence</option>{evidence.map(x=><option key={x.id} value={x.id}>{x.supported_fact}</option>)}</select></label><label>Export purpose<textarea rows={2} maxLength={1000} value={purpose} onChange={e=>setPurpose(e.target.value)}/></label><div className="record-actions"><button type="button" className="button secondary" disabled={busy||!subject||!purpose.trim()} onClick={()=>void createExport()}>Request governed export</button><button type="button" className="button secondary" disabled={busy||!subject} onClick={()=>void recover()}>Check governed recovery</button></div>{exp?<p>Export <StatusBadge value={exp.status}/> {exp.byte_count!=null?`· ${exp.byte_count} bytes`:""}</p>:null}{rec?<p>Recovery <StatusBadge value={rec.status}/></p>:null}<p aria-live="polite" role="status">{message}</p></Surface>;
}
