from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


def test_production_compose_keeps_backend_and_database_private():
    compose = (ROOT / "docker-compose.production.yml").read_text(encoding="utf-8")
    assert "internal: true" in compose
    assert "backend:" in compose and "postgres:" in compose
    assert "DATABASE_PASSWORD_FILE" in compose
    assert "SATCO_OBJECT_HEALTH_URL" in compose
    assert "SATCO_OBJECT_HEALTH_CA_FILE" in compose
    assert "SATCO_MONITORING_TOKEN_FILE" in compose
    assert "SATCO_OPS_MODE_FILE" in compose
    assert "SATCO_OPS_MODE_HMAC_KEY_FILE" in compose
    assert "satco_ops_mode:/run/satco-ops:ro" in compose
    assert "ops-mode-init:" in compose
    assert "set-ops-mode.sh reconcile" in compose
    assert 'ports: ["80:8080", "443:8443"]' in compose
    assert 'user: "101:101"' in compose
    assert "cap_drop: [ALL]" in compose
    assert "ALEMBIC_DATABASE_URL_FILE: /run/secrets/migration_database_url" in compose
    assert "SATCO_RUNTIME_DATABASE_ROLE: satco_runtime" in compose
    assert "RUNTIME_DATABASE_ROLE: satco_runtime" in compose
    assert "SATCO_PREFLIGHT_PHASE=before" in compose
    assert 'export ALEMBIC_DATABASE_URL="$$(cat "$$ALEMBIC_DATABASE_URL_FILE")"' in compose
    assert "preupgrade_recovery_set" in compose
    assert "POSTGRES_PASSWORD_FILE: /run/secrets/schema_owner_db_password" in compose
    assert "service_healthy" in compose


def test_edge_configuration_has_tls_headers_and_no_object_route():
    config = (ROOT / "ops/nginx/default.conf").read_text(encoding="utf-8")
    assert "listen 8443 ssl" in config
    assert "Strict-Transport-Security" in config
    assert "location /api/v1/" in config
    for accepted_prefix in (
        "auth", "customers", "projects", "engineering-workspaces",
        "engineering-experience-captures", "technical-reports",
        "organizational-memory", "organization-admin", "platform/bootstrap",
    ):
        assert accepted_prefix in config
    assert "operations" not in config
    assert "openapi" not in config
    assert "/docs" not in config
    assert "proxy_pass http://frontend:8080" in config
    assert "proxy_pass http://frontend:80;" not in config
    assert "location /objects" not in config.lower()
    assert "s3" not in config.lower()
    assert "/run/satco-ops/write-blocked" in config
    assert "POST|PUT|PATCH|DELETE" in config


def test_production_application_enforces_host_and_origin_allow_lists():
    main = (ROOT / "backend/app/main.py").read_text(encoding="utf-8")
    assert "TrustedHostMiddleware" in main
    assert "CORSMiddleware" in main
    assert "SATCO_TRUSTED_HOSTS" in main
    assert "SATCO_ALLOWED_ORIGINS" in main


def test_frontend_image_serves_spa_routes_on_the_internal_port():
    dockerfile = (ROOT / "frontend/Dockerfile.production").read_text(encoding="utf-8")
    config = (ROOT / "ops/nginx/frontend.conf").read_text(encoding="utf-8")
    assert "USER nginx" in dockerfile
    assert "EXPOSE 8080" in dockerfile
    assert "ops/nginx/frontend.conf" in dockerfile
    assert "try_files $uri $uri/ /index.html" in config


def test_backend_image_installs_only_the_generated_hash_locked_requirements():
    dockerfile = (ROOT / "backend/Dockerfile.production").read_text(
        encoding="utf-8"
    )
    lock = (ROOT / "backend/requirements.production.lock").read_text(
        encoding="utf-8"
    )
    assert "COPY requirements.production.lock" in dockerfile
    assert "--require-hashes" in dockerfile
    assert "requirements.txt /app/requirements.txt" not in dockerfile
    assert "autogenerated by pip-compile with Python 3.12" in lock
    assert "pip-compile --generate-hashes" in lock
    assert lock.count("--hash=sha256:") >= 1
    assert "python:3.12-slim@sha256:" in dockerfile


def test_all_declared_production_base_images_are_digest_pinned():
    compose = (ROOT / "docker-compose.production.yml").read_text(encoding="utf-8")
    frontend = (ROOT / "frontend/Dockerfile.production").read_text(encoding="utf-8")
    assert "nginx:1.27-alpine@sha256:" in compose
    assert "postgres:17@sha256:" in compose
    assert "node:22-alpine@sha256:" in frontend
    assert "nginx:1.27-alpine@sha256:" in frontend
