import { useEffect, useState, type FormEvent } from "react";
import { api } from "../api/client";
import type { ApiResult, PackageObjectCreateResult, PackageRuleResult, EvidenceRecord, Deliverable } from "../api/types";
import { PackageWorkspaceShell, type PackagePanelProps } from "./PackageWorkspaceShell";

const OBJECTS = ["plc","dcs_controller","esd_controller","control_cabinet","io_channel","hmi","control_logic"] as const;
const RELATIONSHIPS = ["controlled_by","commands","receives_signal_from","sends_signal_to","implemented_in","interlocked_with","trips","initiates","inhibits","participates_in_sequence","monitored_by","generates_alarm_for","executes_logic_for"] as const;
const INPUTS = ["control_philosophy_basis","io_allocation_basis","alarm_interlock_basis","cause_effect_basis","availability_redundancy_basis"] as const;
const DELIVERABLES = ["control_io_list","control_narrative","cause_effect_matrix","alarm_interlock_schedule","control_system_architecture_diagram"] as const;
const EVIDENCE = ["control_philosophy_evidence","io_allocation_evidence","cause_effect_interlock_evidence","deliverable_review_evidence"] as const;
const RULES = ["object_relationship_integrity","required_input_completeness","io_logic_connectivity","evidence_sufficiency","deliverable_readiness"] as const;
const REPRESENTATION = {control_io_list:"spreadsheet",control_narrative:"document",cause_effect_matrix:"document",alarm_interlock_schedule:"spreadsheet",control_system_architecture_diagram:"cad"} as const;
type ObjectOption={handle:string;label:string};
type ContextOption={context_handle:number;subject_handle:number;context_version:number;label:string};

export function ControlAutomationPackagePanel({ state = "UNAVAILABLE", projectId, workspaceId }: Readonly<PackagePanelProps>) {
  const [objectType,setObjectType]=useState<(typeof OBJECTS)[number]>("plc");
  const [displayValue,setDisplayValue]=useState("");
  const [rationale,setRationale]=useState("");
  const [creation,setCreation]=useState<ApiResult<PackageObjectCreateResult>|null>(null);
  const [assessment,setAssessment]=useState<ApiResult<PackageRuleResult>|null>(null);
  const [relationshipType,setRelationshipType]=useState<(typeof RELATIONSHIPS)[number]>("controlled_by");
  const [sourceId,setSourceId]=useState(""); const [targetId,setTargetId]=useState("");
  const [relationshipRationale,setRelationshipRationale]=useState("");
  const [contextInput,setContextInput]=useState<(typeof INPUTS)[number]>("control_philosophy_basis");
  const [contextSelection,setContextSelection]=useState("");
  const [configurationRevision,setConfigurationRevision]=useState<number|null>(null);
  const [contextRationale,setContextRationale]=useState("");
  const [evidenceInput,setEvidenceInput]=useState<(typeof EVIDENCE)[number]>("control_philosophy_evidence");
  const [evidenceId,setEvidenceId]=useState("");
  const [evidenceRationale,setEvidenceRationale]=useState("");
  const [deliverableType,setDeliverableType]=useState<(typeof DELIVERABLES)[number]>("control_io_list");
  const [deliverableCode,setDeliverableCode]=useState(""); const [deliverableTitle,setDeliverableTitle]=useState("");
  const [externalLabel,setExternalLabel]=useState(""); const [deliverableRationale,setDeliverableRationale]=useState("");
  const [readinessDeliverableId,setReadinessDeliverableId]=useState(""); const [readinessRevisionId,setReadinessRevisionId]=useState("");
  const [readinessObjectIds,setReadinessObjectIds]=useState(""); const [readinessEvidenceIds,setReadinessEvidenceIds]=useState("");
  const [journeyStatus,setJourneyStatus]=useState<string|null>(null);
  const [objectOptions,setObjectOptions]=useState<ObjectOption[]>([]); const [evidenceOptions,setEvidenceOptions]=useState<EvidenceRecord[]>([]); const [deliverableOptions,setDeliverableOptions]=useState<Deliverable[]>([]); const [contextOptions,setContextOptions]=useState<ContextOption[]>([]);
  useEffect(()=>{setObjectOptions([]);setEvidenceOptions([]);setDeliverableOptions([]);setContextOptions([]);setConfigurationRevision(null);setContextSelection("");if(!projectId||!workspaceId)return;void Promise.all([api.engineeringObjectOptions(projectId,workspaceId),api.evidence(projectId,workspaceId),api.deliverables(projectId),api.packageContextBindingOptions(projectId,workspaceId),api.workspacePackageApplicability(workspaceId)]).then(([objects,evidence,deliverables,context,applicability])=>{if(objects.state==="success")setObjectOptions(objects.data.items);if(evidence.state==="success")setEvidenceOptions(evidence.data.items);if(deliverables.state==="success"&&deliverables.data.outcome==="success")setDeliverableOptions(deliverables.data.items.filter(item=>item.workspace_id===workspaceId));if(context.state==="success")setContextOptions(context.data.items);setConfigurationRevision(applicability.state==="success"&&applicability.data.project_configuration_revision!=null&&applicability.data.project_configuration_revision>0?applicability.data.project_configuration_revision:null);});},[projectId,workspaceId]);
  const splitIds=(value:string)=>value.split(",").map(item=>item.trim()).filter(Boolean).sort();
  async function report(name:string,promise:Promise<ApiResult<unknown>>){const result=await promise;setJourneyStatus(`${name}: ${result.state}`);}
  async function createObject(event:FormEvent){event.preventDefault();if(!projectId||!workspaceId)return;setCreation(await api.createControlAutomationObject(projectId,workspaceId,{declaration_id:`control_automation.object.${objectType}`,primary_identifier_display_value:displayValue,primary_identifier_evidence_references:[],steward_id:null,rationale}));}
  async function evaluate(){if(!projectId||!workspaceId)return;setAssessment(await api.evaluateControlAutomationRule(projectId,workspaceId,{hook_id:"control_automation.required_input_completeness",hook_version:"1.0.0",envelope:{objects:[],relationships:[],deliverables:[],contexts:[],evidence:[],missing_required_ids:[],partial:true,protected:false,stale:false}}));}
  async function createRelationship(event:FormEvent){event.preventDefault();if(!projectId||!workspaceId||!sourceId||!targetId)return;await report("Relationship",api.createControlAutomationRelationship(projectId,workspaceId,{declaration_id:`control_automation.relationship.${relationshipType}`,source_object_id:sourceId,target_object_id:targetId,evidence_references:[],steward_id:null,rationale:relationshipRationale}));}
  async function bindContext(event:FormEvent){event.preventDefault();const option=contextOptions.find(item=>`${item.context_handle}:${item.subject_handle}`===contextSelection);if(!projectId||!workspaceId||!option||configurationRevision==null)return;await report("Context binding",api.bindControlAutomationContext(projectId,workspaceId,{input_declaration_id:`control_automation.${contextInput}.input`,context_id:option.context_handle,context_subject_reference_id:option.subject_handle,expected_context_version:option.context_version,expected_configuration_revision:configurationRevision,rationale:contextRationale}));}
  async function bindEvidence(event:FormEvent){event.preventDefault();const evidence=evidenceOptions.find(item=>item.id===evidenceId);if(!projectId||!workspaceId||!evidence||evidence.version<1||configurationRevision==null)return;await report("Evidence binding",api.bindControlAutomationEvidence(projectId,workspaceId,{input_declaration_id:`control_automation.${evidenceInput}.input`,evidence_id:evidence.id,expected_evidence_version:evidence.version,expected_configuration_revision:configurationRevision,rationale:evidenceRationale}));}
  async function createDeliverable(event:FormEvent){event.preventDefault();if(!projectId||!workspaceId)return;await report("Deliverable",api.createControlAutomationDeliverable(projectId,workspaceId,{declaration_id:`control_automation.deliverable.${deliverableType}`,code:deliverableCode,title:deliverableTitle,discipline:"industrial_automation",deliverable_type:deliverableType,external_authority:REPRESENTATION[deliverableType],workspace_id:workspaceId,initial_external_label:externalLabel,rationale:deliverableRationale}));}
  async function evaluateReadiness(event:FormEvent){event.preventDefault();if(!projectId||!workspaceId||!readinessDeliverableId||!readinessRevisionId||configurationRevision==null)return;await report("Deliverable readiness",api.controlAutomationReadiness(projectId,workspaceId,readinessDeliverableId,readinessRevisionId,configurationRevision,splitIds(readinessObjectIds),splitIds(readinessEvidenceIds)));}
  return <PackageWorkspaceShell title="Control & Automation V1" state={state}>
    <p>Server-authorized Control & Automation engineering package. Deterministic checks are bounded, non-authoritative, and cannot generate executable control-system content.</p>
    <div className="package-catalog-grid">
      <section><h3>Objects · 7</h3><ul>{OBJECTS.map(x=><li key={x}>{x.replaceAll("_"," ")}</li>)}</ul></section>
      <section><h3>Relationships · 13</h3><ul>{RELATIONSHIPS.map(x=><li key={x}>{x.replaceAll("_"," ")}</li>)}</ul></section>
      <section><h3>Inputs / Context · 5</h3><ul>{INPUTS.map(x=><li key={x}>{x.replaceAll("_"," ")}</li>)}</ul></section>
      <section><h3>Evidence & Deliverables</h3><p>{EVIDENCE.length} exact evidence requirements · {DELIVERABLES.length} deliverables</p><ul>{DELIVERABLES.map(x=><li key={x}>{x.replaceAll("_"," ")}</li>)}</ul></section>
      <section><h3>Deterministic Guidance · 5</h3><ul>{RULES.map(x=><li key={x}>{x.replaceAll("_"," ")}</li>)}</ul><button type="button" className="button secondary" onClick={evaluate}>Evaluate bounded readiness</button>{assessment?.state==="success"?<p role="status">{assessment.data.status}</p>:assessment?<p role="alert">Evaluation {assessment.state}</p>:null}</section>
    </div>
    <form className="bootstrap-form" onSubmit={createObject}><h3>Create Object with required primary Identifier</h3><label>Object declaration<select value={objectType} onChange={e=>setObjectType(e.target.value as typeof objectType)}>{OBJECTS.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label>Primary identifier<input required minLength={1} maxLength={128} value={displayValue} onChange={e=>setDisplayValue(e.target.value)}/></label><label>Rationale<textarea required minLength={1} maxLength={2000} value={rationale} onChange={e=>setRationale(e.target.value)}/></label><button className="button primary">Create atomic Object + Identifier</button>{creation?.state==="success"?<p role="status">Created {creation.data.primary_identifier.display_value}</p>:creation?<p role="alert">Operation {creation.state}</p>:null}</form>
    <form className="bootstrap-form" onSubmit={createRelationship}><h3>Create exact Relationship</h3><label>Relationship declaration<select value={relationshipType} onChange={e=>setRelationshipType(e.target.value as typeof relationshipType)}>{RELATIONSHIPS.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label>Source Object<select required value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">Select authorized object</option>{objectOptions.map(item=><option key={item.handle} value={item.handle}>{item.label}</option>)}</select></label><label>Target Object<select required value={targetId} onChange={e=>setTargetId(e.target.value)}><option value="">Select authorized object</option>{objectOptions.map(item=><option key={item.handle} value={item.handle}>{item.label}</option>)}</select></label><label>Rationale<textarea required value={relationshipRationale} onChange={e=>setRelationshipRationale(e.target.value)}/></label><button className="button primary" disabled={!sourceId||!targetId}>Create governed Relationship</button></form>
    <form className="bootstrap-form" onSubmit={bindContext}><h3>Bind exact Context input</h3><label>Context input<select value={contextInput} onChange={e=>setContextInput(e.target.value as typeof contextInput)}>{INPUTS.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label>Engineering Context subject<select required value={contextSelection} onChange={e=>setContextSelection(e.target.value)}><option value="">Select authorized Context subject</option>{contextOptions.map(item=><option key={`${item.context_handle}:${item.subject_handle}`} value={`${item.context_handle}:${item.subject_handle}`}>{item.label}</option>)}</select></label><p>Configuration revision: {configurationRevision??"unavailable"} (authorized package state)</p><label>Rationale<textarea required value={contextRationale} onChange={e=>setContextRationale(e.target.value)}/></label><button className="button primary" disabled={configurationRevision==null||!contextSelection}>Bind Context declaration</button></form>
    <form className="bootstrap-form" onSubmit={bindEvidence}><h3>Bind exact Evidence input</h3><label>Evidence input<select value={evidenceInput} onChange={e=>setEvidenceInput(e.target.value as typeof evidenceInput)}>{EVIDENCE.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label>Evidence<select required value={evidenceId} onChange={e=>setEvidenceId(e.target.value)}><option value="">Select authorized evidence</option>{evidenceOptions.map(item=><option key={item.id} value={item.id}>{item.supported_fact}</option>)}</select></label><label>Rationale<textarea required value={evidenceRationale} onChange={e=>setEvidenceRationale(e.target.value)}/></label><button className="button primary" disabled={configurationRevision==null||!evidenceOptions.some(item=>item.id===evidenceId&&item.version>0)}>Bind Evidence declaration</button></form>
    <form className="bootstrap-form" onSubmit={createDeliverable}><h3>Create governed Deliverable</h3><label>Deliverable declaration<select value={deliverableType} onChange={e=>setDeliverableType(e.target.value as typeof deliverableType)}>{DELIVERABLES.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label><label>Code<input required value={deliverableCode} onChange={e=>setDeliverableCode(e.target.value)}/></label><label>Title<input required value={deliverableTitle} onChange={e=>setDeliverableTitle(e.target.value)}/></label><label>Initial external label<input required value={externalLabel} onChange={e=>setExternalLabel(e.target.value)}/></label><label>Rationale<textarea required value={deliverableRationale} onChange={e=>setDeliverableRationale(e.target.value)}/></label><button className="button primary">Create package Deliverable</button></form>
    <form className="bootstrap-form" onSubmit={evaluateReadiness}><h3>Review exact Deliverable readiness</h3><label>Deliverable<select required value={readinessDeliverableId} onChange={e=>{setReadinessDeliverableId(e.target.value);setReadinessRevisionId(deliverableOptions.find(item=>item.id===e.target.value)?.current_revision.id??"");}}><option value="">Select authorized deliverable</option>{deliverableOptions.map(item=><option key={item.id} value={item.id}>{item.code} — {item.title}</option>)}</select></label><fieldset><legend>Objects</legend>{objectOptions.map(item=><label key={item.handle}><input type="checkbox" checked={splitIds(readinessObjectIds).includes(item.handle)} onChange={()=>setReadinessObjectIds(current=>{const ids=splitIds(current);return (ids.includes(item.handle)?ids.filter(id=>id!==item.handle):[...ids,item.handle]).join(",")})}/>{item.label}</label>)}</fieldset><fieldset><legend>Evidence</legend>{evidenceOptions.map(item=><label key={item.id}><input type="checkbox" checked={splitIds(readinessEvidenceIds).includes(item.id)} onChange={()=>setReadinessEvidenceIds(current=>{const ids=splitIds(current);return (ids.includes(item.id)?ids.filter(id=>id!==item.id):[...ids,item.id]).join(",")})}/>{item.supported_fact}</label>)}</fieldset><button className="button secondary" disabled={configurationRevision==null||!readinessDeliverableId||!readinessRevisionId}>Evaluate exact readiness</button></form>
    {journeyStatus?<p role={journeyStatus.endsWith("success")?"status":"alert"}>{journeyStatus}</p>:null}
  </PackageWorkspaceShell>;
}
