import { useState, type FormEvent } from "react";
import { ArrowLeft, Bot, CheckCircle2, CircleHelp, Sparkles, TriangleAlert } from "lucide-react";
import { Link, useSearchParams } from "react-router-dom";
import { api } from "../api/client";
import type { AdviceResponse, ApiResult } from "../api/types";
import { ErrorState, ProtectedState, StatusBadge } from "../components/States";
import { PageHeader, Surface } from "../components/Page";

export function AssistantPage() {
  const [parameters] = useSearchParams();
  const captureId = parameters.get("capture_id") ?? "";
  const projectId = parameters.get("project_id") ?? "";
  const workspaceId = parameters.get("workspace_id") ?? "";
  const contextual = Boolean(captureId && Number(projectId) > 0 && Number(workspaceId) > 0);
  const [instruction, setInstruction] = useState("");
  const [result, setResult] = useState<ApiResult<AdviceResponse> | null>(null);
  const [busy, setBusy] = useState(false);

  async function submit(event: FormEvent) {
    event.preventDefault();
    if (!contextual) return;
    setBusy(true);
    const response = await api.advice({ capture_id: captureId, project_id: Number(projectId), workspace_id: Number(workspaceId), human_instruction: instruction });
    setResult(response); setBusy(false);
  }
  const response = result?.state === "success" ? result.data : null;
  return <div className="page"><PageHeader eyebrow="PATCH-035 · Human controlled" title="AI Capture Assistant" description="Request one bounded advisory refinement. You remain responsible for review and every engineering decision." action={<span className="ai-label"><Sparkles />AI advisory · never authoritative</span>} />
    {!contextual ? <Surface title="Select a Capture first" subtitle="No engineering record is disclosed from untrusted identifiers."><div className="context-guidance"><Bot /><p>Open an authorized Project, create or select an Engineering Capture, then choose AI advice. SATCO will carry the navigation context and independently reauthorize it.</p><Link className="button primary" to="/projects">Go to Projects</Link></div></Surface> :
      <div className="assistant-layout"><Surface title="Prepare advice" subtitle="Canonical Capture access is checked before any provider receives context."><Link className="text-link back-link" to={`/projects/${projectId}`}><ArrowLeft size={16} />Return to Project</Link><dl className="context-summary"><div><dt>Project</dt><dd>Current authorized Project</dd></div><div><dt>Workspace</dt><dd>Selected engineering context</dd></div><div><dt>Capture</dt><dd>Selected canonical Capture</dd></div></dl><form className="assistant-form" onSubmit={submit}><label>Human instruction<textarea value={instruction} onChange={(event) => setInstruction(event.target.value)} required minLength={1} maxLength={2000} rows={6} placeholder="State what should be clarified or refined. Do not ask AI to approve engineering work." /></label><button className="button primary full" disabled={busy}><Sparkles size={17} />{busy ? "Authorizing and preparing…" : "Prepare advisory refinement"}</button></form></Surface><section className="advice-panel" aria-live="polite">{!result && <div className="advice-empty"><Bot /><h2>AI work appears here</h2><p>Suggestions, uncertainty, limitations, and attribution stay visually separate from canonical facts.</p></div>}{result?.state === "protected" || result?.state === "invalid" ? <ProtectedState /> : result && result.state !== "success" ? <ErrorState unavailable={result.state === "unavailable"} /> : null}{response?.outcome === "success" && <div className="advice-result"><header><div><span className="eyebrow">Advisory proposal</span><h2>Capture refinement</h2></div><StatusBadge value={response.proposal.confidence} /></header><div className="suggested-text">{response.proposal.suggested_text}</div><AdviceList icon={CheckCircle2} title="Observations" items={response.proposal.observations} /><AdviceList icon={CircleHelp} title="Assumptions & missing information" items={[...response.proposal.assumptions, ...response.proposal.missing_information]} /><AdviceList icon={TriangleAlert} title="Limitations" items={response.proposal.limitations} /><div className="next-step"><strong>Recommended next step</strong><p>{response.proposal.recommended_next_step}</p></div><footer>Generated by {response.proposal.provider_attribution.provider_id} / {response.proposal.provider_attribution.model_id} · Capture v{response.proposal.capture_attribution.version}</footer></div>}{response?.outcome === "refused" && <ErrorState />}{response && ["disabled", "unavailable"].includes(response.outcome) && <ErrorState unavailable />}{response && ["protected_not_found", "invalid_request"].includes(response.outcome) && <ProtectedState />}</section></div>}
  </div>;
}

function AdviceList({ icon: Icon, title, items }: { icon: typeof CheckCircle2; title: string; items: string[] }) {
  if (!items.length) return null;
  return <section className="advice-section"><h3><Icon />{title}</h3><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></section>;
}
