import { useEffect, useState } from "react";
import { ArrowLeft, BookMarked, BriefcaseBusiness, FileCheck2, ShieldCheck } from "lucide-react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { api } from "../api/client";
import type { ApiResult, JournalWorkspace, MemoryDetailResult, MemoryPage, Project, Workspace } from "../api/types";
import { EmptyState, ErrorState, LoadingState, ProtectedState, StatusBadge } from "../components/States";
import { PageHeader, Surface } from "../components/Page";

function Boundary<T>({ value, render, empty }: { value: ApiResult<T> | null; render: (x: T) => React.ReactNode; empty?: boolean }) { if (!value) return <LoadingState label="Choose an authorized context to begin." />; if (value.state === "protected" || value.state === "invalid") return <ProtectedState />; if (value.state !== "success") return <ErrorState unavailable={value.state === "unavailable"} />; if (empty) return <EmptyState title="No visible records" detail="No authorized records were returned for this context." />; return render(value.data); }

export function JournalPage() { const [value, setValue] = useState<ApiResult<JournalWorkspace> | null>(null); useEffect(() => { void api.journal().then(setValue); }, []); return <div className="page"><PageHeader eyebrow="Human-first engineering record" title="Engineering Workspace" description="Review the bounded Journal presentation without creating shadow engineering state." /><Surface title="Journal"><Boundary value={value} render={(d) => <div className="journal-summary"><span className="widget-icon"><BriefcaseBusiness /></span><div><span className="eyebrow">{d.availability}</span><h3>{d.view.replaceAll("_", " ")}</h3><p>Result state: {d.result_state.replaceAll("_", " ")}</p></div></div>} /></Surface></div>; }

function MemoryDetail({ id }: { id: string }) {
  const [value, setValue] = useState<ApiResult<MemoryDetailResult> | null>(null);
  useEffect(() => { void api.memoryDetail(id).then(setValue); }, [id]);
  if (!value) return <LoadingState label="Reauthorizing active Memory and its source…" />;
  if (value.state === "protected" || value.state === "invalid") return <ProtectedState />;
  if (value.state !== "success" || value.data.outcome !== "success" || !value.data.item) return <ErrorState unavailable={value.state === "unavailable"} />;
  const item = value.data.item; const source = item.projection;
  return <><Link className="text-link back-link" to={`/memory?project_id=${item.summary.project_id ?? ""}&workspace_id=${item.summary.workspace_id}`}><ArrowLeft size={16} />Back to active Memory</Link><PageHeader eyebrow="Governed engineering reference" title={source.purpose.replaceAll("_", " ")} description="Deliberate Human consultation only — this view creates no new engineering authority." action={<StatusBadge value={item.summary.standing} />} /><div className="memory-detail-grid"><Surface title="Admitted engineering content" subtitle={`Accepted Report version ${source.accepted_aggregate_version}`}><div className="report-content"><section><h3>Engineering scope</h3><p>{source.content.engineering_scope}</p></section><section><h3>Technical content</h3><p>{source.content.technical_content}</p></section><section><h3>Uncertainty</h3><p>{source.content.uncertainty}</p></section><section><h3>Conclusions</h3><p>{source.content.conclusions}</p></section>{source.content.limitations.length ? <section><h3>Limitations</h3><ul>{source.content.limitations.map((x) => <li key={x}>{x}</li>)}</ul></section> : null}</div></Surface><div><Surface title="Authority and attribution"><div className="memory-facts"><div><span>Standing</span><strong>Active approved Memory</strong></div><div><span>Admitted by</span><strong>Authorized Human {item.summary.admitted_by_id}</strong></div><div><span>Admission rationale</span><strong>{item.admission_rationale}</strong></div><div><span>Accepted source</span><Link className="text-link" to={`/reports/${source.report_id}?project_id=${source.project_id ?? ""}&workspace_id=${source.workspace_id}`}>Open exact Technical Report</Link></div></div></Surface><Surface title="Reuse restrictions">{item.reuse_restrictions.length ? <ul className="governance-list">{item.reuse_restrictions.map((x) => <li key={x}>{x}</li>)}</ul> : <p className="authority-copy">No additional Memory-specific restriction was recorded. Source and scope authorization still apply.</p>}</Surface><Surface title="Authorized provenance" subtitle="All entries were independently reauthorized for this consultation.">{item.safe_provenance.length ? <div className="provenance-list">{item.safe_provenance.map((p) => <article key={p.entry_id}><FileCheck2 size={16} /><div><strong>{p.source_type.replaceAll("_", " ")}</strong><span>{p.reliance_role} · verified {p.source_integrity_algorithm}</span></div></article>)}</div> : <p className="authority-copy">No provenance was disclosed.</p>}</Surface></div></div><div className="consultation-callout" role="note"><ShieldCheck /><div><strong>Responsible Human consultation</strong><span>Keep standing, source attribution, limitations, and restrictions attached. Consultation does not approve, mutate, or incorporate this Memory into another canonical record.</span></div></div></>;
}

function MemoryList() {
  const [params, setParams] = useSearchParams(); const projectId = Number(params.get("project_id") || 0); const workspaceId = Number(params.get("workspace_id") || 0);
  const [projects, setProjects] = useState<ApiResult<{ items: Project[] }> | null>(null); const [workspaces, setWorkspaces] = useState<ApiResult<{ items: Workspace[]; total: number }> | null>(null); const [value, setValue] = useState<ApiResult<MemoryPage> | null>(null);
  useEffect(() => { void api.projects().then(setProjects); }, []); useEffect(() => { if (projectId) void api.workspaces(projectId).then(setWorkspaces); else setWorkspaces(null); }, [projectId]); useEffect(() => { if (workspaceId) void api.memory(workspaceId, projectId || undefined).then(setValue); else setValue(null); }, [workspaceId, projectId]);
  const projectItems = projects?.state === "success" ? projects.data.items : []; const workspaceItems = workspaces?.state === "success" ? workspaces.data.items : []; const items = value?.state === "success" ? value.data.page?.items ?? [] : [];
  function selectProject(id: number) { const next = new URLSearchParams(); if (id) next.set("project_id", String(id)); setParams(next); }
  function selectWorkspace(id: number) { const next = new URLSearchParams(params); if (id) next.set("workspace_id", String(id)); else next.delete("workspace_id"); setParams(next); }
  return <><PageHeader eyebrow="Human-admitted knowledge" title="Organizational Memory" description="Find and deliberately consult active approved Memory with its source authority intact." /><Surface title="Authorized engineering context"><div className="report-context"><label>Project<select value={projectId || ""} onChange={(e) => selectProject(Number(e.target.value))}><option value="">Select Project</option>{projectItems.map((p) => <option key={p.id} value={p.id}>{p.project_code} · {p.name}</option>)}</select></label><label>Engineering Workspace<select disabled={!projectId} value={workspaceId || ""} onChange={(e) => selectWorkspace(Number(e.target.value))}><option value="">Select Workspace</option>{workspaceItems.map((w) => <option key={w.id} value={w.id}>{w.display_name}</option>)}</select></label></div></Surface>{!workspaceId ? <EmptyState title="Choose a Project and Workspace" detail="SATCO will request only active Memory authorized for that context." /> : <Boundary value={value} empty={value?.state === "success" && !items.length} render={() => <div className="record-grid">{items.map((m) => <Link className="surface record-card" key={m.memory_id} to={`/memory/${m.memory_id}?project_id=${m.project_id ?? ""}&workspace_id=${m.workspace_id}`}><BookMarked /><div><span className="eyebrow">{m.purpose.replaceAll("_", " ")}</span><h2>Governed Memory</h2><p>Accepted Report · active since {new Date(m.admitted_at).toLocaleDateString()}</p></div><StatusBadge value={m.standing} /></Link>)}</div>} />}</>;
}

export function MemoryPage() { const { memoryId } = useParams(); return <div className="page memory-page">{memoryId ? <MemoryDetail id={memoryId} /> : <MemoryList />}</div>; }
