import { useEffect, useState, type FormEvent } from "react";
import { BookMarked, BriefcaseBusiness, Search } from "lucide-react";
import { api } from "../api/client";
import type { ApiResult, JournalWorkspace, MemoryPage } from "../api/types";
import { EmptyState, ErrorState, LoadingState, ProtectedState, StatusBadge } from "../components/States";
import { PageHeader, Surface } from "../components/Page";

function ScopeForm({ onApply, needsWorkspace = false }: { onApply: (project?: number, workspace?: number) => void; needsWorkspace?: boolean }) { const [project, setProject] = useState(""); const [workspace, setWorkspace] = useState(""); function submit(e: FormEvent) { e.preventDefault(); onApply(project ? Number(project) : undefined, workspace ? Number(workspace) : undefined); } return <form className="scope-form" onSubmit={submit}><label>Project ID<input inputMode="numeric" value={project} onChange={(e) => setProject(e.target.value)} placeholder="Authorized Project" /></label>{needsWorkspace && <label>Workspace ID<input inputMode="numeric" required value={workspace} onChange={(e) => setWorkspace(e.target.value)} placeholder="Required Workspace" /></label>}<button className="button secondary"><Search size={16} />Load context</button></form>; }
function Boundary<T>({ value, render, empty }: { value: ApiResult<T> | null; render: (x: T) => React.ReactNode; empty?: boolean }) { if (!value) return <LoadingState label="Choose an authorized context to begin." />; if (value.state === "protected" || value.state === "invalid") return <ProtectedState />; if (value.state !== "success") return <ErrorState unavailable={value.state === "unavailable"} />; if (empty) return <EmptyState title="No visible records" detail="No authorized records were returned for this context." />; return render(value.data); }

export function JournalPage() { const [value, setValue] = useState<ApiResult<JournalWorkspace> | null>(null); useEffect(() => { void api.journal().then(setValue); }, []); return <div className="page"><PageHeader eyebrow="Human-first engineering record" title="Engineering Workspace" description="Review the bounded Journal presentation without creating shadow engineering state." /><Surface title="Journal"><ScopeForm onApply={(p) => void api.journal(p).then(setValue)} /><Boundary value={value} render={(d) => <div className="journal-summary"><span className="widget-icon"><BriefcaseBusiness /></span><div><span className="eyebrow">{d.availability}</span><h3>{d.view.replaceAll("_", " ")}</h3><p>Result state: {d.result_state.replaceAll("_", " ")}</p></div></div>} /></Surface></div>; }

export function MemoryPage() { const [value, setValue] = useState<ApiResult<MemoryPage> | null>(null); const items = value?.state === "success" ? value.data.page?.items ?? [] : []; return <div className="page"><PageHeader eyebrow="Human-admitted knowledge" title="Organizational Memory" description="Active approved memory remains bound to current source authorization and provenance." /><Surface title="Memory context"><ScopeForm needsWorkspace onApply={(p, w) => w && void api.memory(w, p).then(setValue)} /></Surface><Boundary value={value} empty={value?.state === "success" && !items.length} render={() => <div className="record-grid">{items.map((m) => <article className="surface record-card" key={m.memory_id}><BookMarked /><div><span className="eyebrow">{m.purpose.replaceAll("_", " ")}</span><h2>Memory {m.memory_id.slice(0, 8)}</h2><p>Source report {m.source_report_id.slice(0, 8)} · Version {m.version}</p></div><StatusBadge value={m.standing} /></article>)}</div>} /></div>; }
