import { useState, type FormEvent } from "react";
import { ArrowRight, LockKeyhole } from "lucide-react";
import { Link, Navigate, useLocation, useNavigate } from "react-router-dom";
import { useAuth } from "../auth/AuthProvider";

export function LoginPage() {
  const auth = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [code, setCode] = useState(""); const [error, setError] = useState(false); const [busy, setBusy] = useState(false);
  if (auth.status === "authenticated") return <Navigate to="/" replace />;
  const destination = (location.state as { from?: string } | null)?.from ?? "/";
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(false); const outcome = await auth.login(username, password); setBusy(false); if (outcome === "authenticated") navigate(destination, { replace: true }); else if (outcome === "failed") setError(true); }
  async function submitMfa(event: FormEvent) { event.preventDefault(); setBusy(true); setError(false); const outcome = await auth.completeMfa(code); setBusy(false); if (outcome === "authenticated") navigate(destination, { replace: true }); else if (outcome === "failed") setError(true); }
  async function continueAfterRecovery() { setBusy(true); await auth.acknowledgeRecoveryCodes(); setBusy(false); navigate(destination, { replace: true }); }

  if (auth.status === "mfa_required" && auth.mfa) return <main className="login-page"><section className="login-brand"><div className="brand-mark large">S</div><span className="eyebrow">SATCO V1</span><h1>Required assurance.<br /><em>Human verified.</em></h1><p>Complete the Organization-required authentication step before a browser session is created.</p></section><section className="login-panel"><form onSubmit={submitMfa}><div className="lock-badge"><LockKeyhole /></div><span className="eyebrow">Multi-factor authentication</span><h2>{auth.mfa.enrollmentRequired ? "Secure your account" : "Enter your authenticator code"}</h2>{auth.mfa.enrollmentRequired && auth.mfa.enrollment ? <><p>Add this account to your authenticator using the provisioning URI or setup secret. The factor remains inactive until the code is verified.</p><div className="security-secret"><span>Setup secret</span><code>{auth.mfa.enrollment.secret}</code><a className="text-link" href={auth.mfa.enrollment.provisioningUri}>Open in authenticator</a></div></> : <p>Enter the current six-digit code from your registered authenticator.</p>}<label>Authenticator code<input value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, "").slice(0, 6))} inputMode="numeric" autoComplete="one-time-code" pattern="\d{6}" minLength={6} maxLength={6} required autoFocus /></label>{error && <div className="form-error" role="alert">Verification was not accepted. Request a new login challenge if it expired.</div>}<button className="button primary full" disabled={busy}>{busy ? "Verifying…" : "Verify and continue"}<ArrowRight size={18} /></button><button className="button ghost full" type="button" onClick={auth.cancelMfa} disabled={busy}>Cancel secure login</button></form></section></main>;

  if (auth.status === "recovery_required" && auth.mfa) return <main className="login-page"><section className="login-brand"><div className="brand-mark large">S</div><span className="eyebrow">SATCO V1</span><h1>Recovery ready.<br /><em>Store it safely.</em></h1><p>These recovery codes are shown once. They are Human-controlled security credentials and must be kept outside the browser.</p></section><section className="login-panel"><div className="recovery-panel"><div className="lock-badge"><LockKeyhole /></div><span className="eyebrow">One-time recovery codes</span><h2>Save your recovery codes</h2><p>Each code can be used only once. Do not place them in localStorage, sessionStorage, project notes, or shared messages.</p><ol className="recovery-code-list">{auth.mfa.recoveryCodes.map((recoveryCode) => <li key={recoveryCode}><code>{recoveryCode}</code></li>)}</ol><button className="button primary full" type="button" onClick={() => void continueAfterRecovery()} disabled={busy}>{busy ? "Securing workspace…" : "I have saved these codes"}<ArrowRight size={18} /></button></div></section></main>;
  return <main className="login-page"><section className="login-brand"><div className="brand-mark large">S</div><span className="eyebrow">SATCO V1</span><h1>Engineering intelligence.<br /><em>Human governed.</em></h1><p>Enter the command center for projects, evidence, technical knowledge, and bounded AI assistance.</p><div className="trust-list"><span>Canonical engineering context</span><span>Protected Organization scope</span><span>Human authority preserved</span></div></section><section className="login-panel"><form onSubmit={submit}><div className="lock-badge"><LockKeyhole /></div><span className="eyebrow">Secure access</span><h2>Welcome back</h2><p>Use your SATCO credentials. Your Organization context is resolved securely after authentication.</p><label>Username<input value={username} onChange={(e) => setUsername(e.target.value)} autoComplete="username" required /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} autoComplete="current-password" required /></label>{error && <div className="form-error" role="alert">Authentication was not accepted.</div>}<button className="button primary full" disabled={busy}>{busy ? "Securing workspace…" : "Enter Command Center"}<ArrowRight size={18} /></button><Link className="text-link" to="/reset">Use a reset credential</Link></form></section></main>;
}
