import { useState, type FormEvent } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { api } from "../api/client";
import { useAuth } from "../auth/AuthProvider";

function CredentialPage({ purpose }: { purpose: "activate" | "reset" }) {
  const [params] = useSearchParams(); const navigate = useNavigate();
  const [token, setToken] = useState(params.get("token") ?? ""); const [password, setPassword] = useState(""); const [state, setState] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); const result = purpose === "activate" ? await api.activateAccount(token, password) : await api.resetAccount(token, password); if (result.state === "success") navigate("/login", { replace: true }); else setState("The credential was not accepted. Request a new one from an administrator."); }
  return <main className="login-page"><section className="login-brand"><div className="brand-mark large">S</div><span className="eyebrow">Governed account access</span><h1>{purpose === "activate" ? "Activate your SATCO account." : "Reset your SATCO password."}</h1><p>Single-use credentials are verified by the server and never retained in this browser.</p></section><section className="login-panel"><form onSubmit={submit}><h2>{purpose === "activate" ? "Account activation" : "Password reset"}</h2><label>One-time credential<input value={token} onChange={(e) => setToken(e.target.value)} minLength={40} autoComplete="one-time-code" required /></label><label>New password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} minLength={12} autoComplete="new-password" required /></label>{state && <div className="form-error" role="alert">{state}</div>}<button className="button primary full">{purpose === "activate" ? "Activate account" : "Set new password"}</button><Link className="text-link" to="/login">Return to sign in</Link></form></section></main>;
}

export function ActivatePage() { return <CredentialPage purpose="activate" />; }
export function ResetPage() { return <CredentialPage purpose="reset" />; }

export function BootstrapPage() {
  const [key, setKey] = useState(""); const [name, setName] = useState(""); const [slug, setSlug] = useState(""); const [username, setUsername] = useState(""); const [email, setEmail] = useState(""); const [token, setToken] = useState<string | null>(null); const [failed, setFailed] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setFailed(false); const result = await api.bootstrapOrganization({ organization_name: name, organization_slug: slug, admin_username: username, admin_email: email }, key); if (result.state === "success" && result.data.one_time_token) setToken(result.data.one_time_token); else setFailed(true); }
  return <main className="login-page"><section className="login-brand"><div className="brand-mark large">S</div><span className="eyebrow">Platform bootstrap</span><h1>Initialize the first governed Organization.</h1><p>This bounded operator workflow is not public registration. The bootstrap credential remains browser-memory only.</p></section><section className="login-panel"><form onSubmit={submit}><h2>Organization and initial admin</h2><label>Platform bootstrap key<input type="password" value={key} onChange={(e) => setKey(e.target.value)} minLength={32} required /></label><label>Organization name<input value={name} onChange={(e) => setName(e.target.value)} minLength={2} required /></label><label>Organization slug<input value={slug} onChange={(e) => setSlug(e.target.value)} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required /></label><label>Admin username<input value={username} onChange={(e) => setUsername(e.target.value)} required /></label><label>Admin email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label>{failed && <div className="form-error" role="alert">Bootstrap was not accepted.</div>}{token ? <div className="one-time-secret" role="status"><strong>Copy this activation credential now</strong><code>{token}</code><span>It will not be shown again.</span></div> : <button className="button primary full">Create governed Organization</button>}<Link className="text-link" to="/login">Return to sign in</Link></form></section></main>;
}

export function AccountPage() {
  const auth = useAuth(); const [current, setCurrent] = useState(""); const [next, setNext] = useState(""); const [message, setMessage] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); const result = await api.changePassword(current, next); if (result.state === "success") { auth.logout(); setMessage("Password changed. Sign in again with the new password."); } else setMessage("Password change was not accepted."); }
  return <div className="page"><header className="page-header"><div><span className="eyebrow">Trusted identity</span><h1>My account</h1><p>{auth.profile?.username} · {auth.profile?.organization.name}</p></div></header><section className="surface account-surface"><form className="bootstrap-form" onSubmit={submit}><h2>Change password</h2><label>Current password<input type="password" value={current} onChange={(e) => setCurrent(e.target.value)} required /></label><label>New password<input type="password" value={next} onChange={(e) => setNext(e.target.value)} minLength={12} required /></label><button className="button primary">Change password and end existing sessions</button>{message && <p role="status">{message}</p>}</form></section></div>;
}
