import { useEffect, useState } from "react";
import { ArrowUpRight, BriefcaseBusiness, CalendarClock, FolderKanban, Gauge, Layers3 } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { api } from "../api/client";
import type { ApiResult, Capture, Paginated, Project, Workspace } from "../api/types";
import { EmptyState, ErrorState, LoadingState, ProtectedState, StatusBadge } from "../components/States";
import { PageHeader, Surface } from "../components/Page";

function ResultBoundary<T>({ result, children, empty }: { result: ApiResult<T> | null; children: (data: T) => React.ReactNode; empty?: (data: T) => boolean }) { if (!result) return <LoadingState />; if (result.state === "protected" || result.state === "invalid") return <ProtectedState />; if (result.state !== "success") return <ErrorState unavailable={result.state === "unavailable"} />; if (empty?.(result.data)) return <EmptyState title="Nothing visible here yet" detail="Authorized engineering records will appear when available." />; return children(result.data); }

export function ProjectsPage() {
  const [result, setResult] = useState<ApiResult<Paginated<Project>> | null>(null); useEffect(() => { void api.projects().then(setResult); }, []);
  return <div className="page"><PageHeader eyebrow="Authorized portfolio" title="Projects" description="Find active engineering work quickly and enter its trusted context." /><ResultBoundary result={result} empty={(d) => !d.items.length}>{(data) => <div className="project-cards">{data.items.map((p) => <Link className="project-card surface" to={`/projects/${p.id}`} key={p.id}><div className="project-card-top"><span className="widget-icon"><FolderKanban /></span><StatusBadge value={p.status} /></div><span className="eyebrow">{p.project_code}</span><h2>{p.name}</h2><p>{p.description || p.customer.name}</p><div className="project-metrics"><span><Gauge />{p.progress}% complete</span><span><CalendarClock />{p.target_completion_date || "No target date"}</span></div><div className="progress-track"><i style={{ width: `${p.progress}%` }} /></div><span className="text-link">Open engineering workspace<ArrowUpRight size={16} /></span></Link>)}</div>}</ResultBoundary></div>;
}

export function ProjectWorkspacePage() {
  const id = Number(useParams().projectId); const [project, setProject] = useState<ApiResult<Project> | null>(null); const [workspaces, setWorkspaces] = useState<ApiResult<{ items: Workspace[]; total: number }> | null>(null); const [captures, setCaptures] = useState<ApiResult<{ items: Capture[]; total: number }> | null>(null);
  useEffect(() => { if (Number.isInteger(id) && id > 0) { void api.project(id).then(setProject); void api.workspaces(id).then(setWorkspaces); void api.captures(id).then(setCaptures); } }, [id]);
  return <div className="page"><ResultBoundary result={project}>{(p) => <><PageHeader eyebrow={`${p.project_code} · ${p.customer.name}`} title={p.name} description={p.description || "Authorized Project engineering workspace."} action={<StatusBadge value={p.status} />} /><div className="workspace-summary"><Surface><span className="eyebrow">Progress</span><strong className="hero-metric">{p.progress}%</strong><div className="progress-track"><i style={{ width: `${p.progress}%` }} /></div></Surface><Surface><span className="eyebrow">Priority</span><strong className="hero-metric small">{p.priority}</strong><span>{p.primary_assignee?.full_name || p.primary_assignee?.username || "Unassigned"}</span></Surface></div><div className="split-grid"><Surface title="Discipline Workspaces" subtitle="Canonical Project context"><ResultBoundary result={workspaces} empty={(d) => !d.items.length}>{(d) => <div className="record-list">{d.items.map((w) => <article key={w.id}><span className="widget-icon"><Layers3 /></span><div><strong>{w.display_name}</strong><span>{w.discipline} · Version {w.version}</span></div><StatusBadge value={w.status} /></article>)}</div>}</ResultBoundary></Surface><Surface title="Recent Captures" subtitle="Authorized engineering experience"><ResultBoundary result={captures} empty={(d) => !d.items.length}>{(d) => <div className="record-list">{d.items.slice(0, 8).map((c) => <article key={c.id}><span className="widget-icon"><BriefcaseBusiness /></span><div><strong>{c.source_kind.replaceAll("_", " ")}</strong><span>{c.discipline || "General"} · Version {c.version}</span></div><StatusBadge value={c.lifecycle} /></article>)}</div>}</ResultBoundary></Surface></div></>}</ResultBoundary></div>;
}
