import { api, authSession, login } from "../api/client";

describe("typed API boundary", () => {
  beforeEach(() => { sessionStorage.clear(); vi.restoreAllMocks(); });
  it("stores access tokens only in session storage", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response(JSON.stringify({ access_token: "trusted" }), { status: 200 }))); expect((await login("engineer", "secret")).state).toBe("success"); expect(authSession.get()).toBe("trusted"); expect(localStorage.length).toBe(0); });
  it("sends bearer authentication without actor or Organization fields", async () => { authSession.set("abc"); const fetchMock = vi.fn().mockResolvedValue(new Response(JSON.stringify({ items: [], total: 0, page: 1, size: 20 }), { status: 200 })); vi.stubGlobal("fetch", fetchMock); await api.projects(); const [url, init] = fetchMock.mock.calls[0]; expect(url).toContain("/projects/"); expect(new Headers(init.headers).get("Authorization")).toBe("Bearer abc"); expect(String(url)).not.toMatch(/actor|organization/i); });
  it.each([[403, "protected"], [404, "protected"], [422, "invalid"], [503, "unavailable"], [500, "error"]])("maps status %s safely", async (status, state) => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response("{}", { status: Number(status) }))); expect((await api.projects()).state).toBe(state); });
  it("clears an expired session without exposing details", async () => { authSession.set("expired"); vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response("{}", { status: 401 }))); expect((await api.me()).state).toBe("protected"); expect(authSession.get()).toBeNull(); });
  it("uses bounded accepted integration paths", async () => { const mock = vi.fn().mockResolvedValue(new Response(JSON.stringify({ items: [], total: 0 }), { status: 200 })); vi.stubGlobal("fetch", mock); await api.workspaces(7); await api.captures(7); await api.reports(12, 7); await api.memory(12, 7); expect(mock.mock.calls.map(([url]) => String(url))).toEqual(expect.arrayContaining([expect.stringContaining("size=20"), expect.stringContaining("page_size=20")])); });
  it("uses trusted-context bootstrap mutation paths without authority fields", async () => { vi.stubGlobal("crypto", { randomUUID: vi.fn().mockReturnValue("00000000-0000-4000-8000-000000000001") }); const mock = vi.fn().mockResolvedValue(new Response(JSON.stringify({ id: 1 }), { status: 200 })); vi.stubGlobal("fetch", mock); await api.createCustomer({ name: "Plant" }); await api.createProject({ name: "Relay", customer_id: 1 }); await api.createWorkspace(2, { discipline: "electrical" }); await api.createCapture({ project_id: 2, workspace_id: 3, source_kind: "observation", original_content: "Observed." }); const calls = mock.mock.calls.map(([url, init]) => ({ url: String(url), body: String(init.body ?? ""), headers: new Headers(init.headers) })); expect(calls.map((call) => call.url)).toEqual(expect.arrayContaining([expect.stringContaining("/customers/"), expect.stringContaining("/projects/2/workspaces"), expect.stringContaining("/engineering-experience-captures")])); expect(calls.map((call) => call.body).join(" ")).not.toMatch(/organization_id|actor_id|owner_id/); expect(calls[3].headers.get("Idempotency-Key")).toBe("00000000-0000-4000-8000-000000000001"); });
  it("maps payload-free closed Memory outcomes without treating them as empty success", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(new Response(JSON.stringify({ outcome: "protected_not_found" }), { status: 200 }))); expect((await api.memory(12, 7)).state).toBe("protected"); });
});
