import { render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { EngineeringExecutionPlanPanel } from "../components/EngineeringExecutionPlanPanel";

const { apiMock } = vi.hoisted(() => ({ apiMock: { executionPlan:vi.fn(), establishExecutionPlan:vi.fn(), createExecutionActivity:vi.fn(), transitionExecutionActivity:vi.fn(), replaceExecutionDependencies:vi.fn(), createExecutionMilestone:vi.fn() } }));
vi.mock("../api/client", () => ({ api:apiMock }));
const project={id:7,name:"Protection renewal",project_code:"SAT-007",description:null,priority:"medium",status:"active",progress:25,customer:{id:1,name:"Customer"},owner:{id:8,username:"owner",full_name:"Project Owner"},primary_assignee:{id:9,username:"engineer",full_name:"Primary Engineer"}} as any;
const workspace={id:3,display_name:"Electrical Engineering",discipline:"electrical"} as any;
const established={outcome:"success",availability:"established",project_id:7,plan_id:"10000000-0000-0000-0000-000000000001",version:2,activities:[{id:"20000000-0000-0000-0000-000000000001",title:"Relay survey",description:null,ordinal:0,workspace_id:3,responsible_user_id:8,target_date:null,completion_basis:"Survey accepted",standing:"planned",version:1,blocker_rationale:null,updated_at:"2026-08-24T00:00:00Z"}],milestones:[],dependencies:[],progress:{completed_count:0,eligible_count:1,percent:0}} as const;
beforeEach(() => { for (const fn of Object.values(apiMock)) fn.mockReset(); apiMock.executionPlan.mockResolvedValue({state:"success",data:established}); apiMock.createExecutionActivity.mockResolvedValue({state:"success",data:{outcome:"success"}}); apiMock.transitionExecutionActivity.mockResolvedValue({state:"success",data:{outcome:"success"}}); });
it("renders real execution facts without raw identity entry and creates a human-rationaled activity", async () => { const user=userEvent.setup(); render(<EngineeringExecutionPlanPanel projectId={7} project={project} workspaces={[workspace]} />); expect(await screen.findByText("Relay survey",{selector:"strong"})).toBeVisible(); expect(screen.queryByLabelText(/organization id|project id|activity id/i)).not.toBeInTheDocument(); const form=screen.getByRole("button",{name:"Add activity"}).closest("form")!; await user.type(within(form).getByLabelText("Activity title"),"Panel testing"); await user.type(within(form).getByLabelText("Completion basis"),"Panels tested"); await user.type(within(form).getByLabelText("Human rationale"),"Engineer set the initial execution work"); await user.click(within(form).getByRole("button",{name:"Add activity"})); expect(apiMock.createExecutionActivity).toHaveBeenCalledWith(7,expect.objectContaining({title:"Panel testing",rationale:"Engineer set the initial execution work",ordinal:1})); });
it("uses a truthful empty state and establishes only with explicit Human rationale", async () => { apiMock.executionPlan.mockResolvedValueOnce({state:"success",data:{outcome:"success",availability:"plan_not_established",project_id:7,allowed_actions:["establish"]}}); apiMock.establishExecutionPlan.mockResolvedValue({state:"success",data:{outcome:"success"}}); const user=userEvent.setup(); render(<EngineeringExecutionPlanPanel projectId={7} project={project} workspaces={[]}/>); expect(await screen.findByText(/Engineering execution is not established/i)).toBeVisible(); await user.type(screen.getByLabelText("Human rationale"),"Establish approved execution plan"); await user.click(screen.getByRole("button",{name:"Establish execution plan"})); expect(apiMock.establishExecutionPlan).toHaveBeenCalledWith(7,{expected_plan_version:0,rationale:"Establish approved execution plan"}); });
it("keeps protected results neutral", async () => { apiMock.executionPlan.mockResolvedValue({state:"protected"}); render(<EngineeringExecutionPlanPanel projectId={7} project={project} workspaces={[]}/>); expect(await screen.findByText("Not available")).toBeVisible(); expect(screen.queryByText("Relay survey")).not.toBeInTheDocument(); });
