import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { EvidenceWorkbench } from "../components/EvidenceWorkbench";
import { RetentionGovernancePanel } from "../components/RetentionGovernancePanel";

export const PATCH055_FRONTEND_VECTORS = ["P055-UX-01","P055-UX-02","P055-UX-03","P055-UX-04","P055-UX-05","P055-UX-06"] as const;
const { apiMock, retentionMock } = vi.hoisted(() => ({
 apiMock:{evidence:vi.fn()},
 retentionMock:{workbench:vi.fn(),createEvidence:vi.fn(),evidenceTransition:vi.fn(),state:vi.fn(),policy:vi.fn(),hold:vi.fn(),release:vi.fn(),disposition:vi.fn(),export:vi.fn(),exportStatus:vi.fn(),recovery:vi.fn(),recoveryStatus:vi.fn(),downloadExport:vi.fn()}
}));
vi.mock("../api/client",()=>({api:apiMock}));
vi.mock("../services/retentionApi",async()=>{const actual=await vi.importActual<typeof import("../services/retentionApi")>("../services/retentionApi");return {...actual,retentionApi:retentionMock};});

const evidence={id:"dddddddd-dddd-4ddd-8ddd-dddddddddddd",organization_id:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",project_id:7,workspace_id:9,lifecycle:"current" as const,source_kind:"engineering_record",source_reference:"field",source_revision:"r1",source_standing:"current",effective_at:null,supported_fact:"Verified relay setting basis",creator_id:11,version:3,created_at:"2026-09-17T00:00:00Z",updated_at:"2026-09-17T00:00:00Z",allowed_actions:[]};
const state={retention_record_id:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",subject:{subject_kind:"evidence" as const,subject_id:evidence.id,organization_id:evidence.organization_id,project_id:7,workspace_id:9},retention_mode:"retain_indefinitely" as const,retention_until:null,policy_basis_code:"human.workbench",basis_rationale:"Human",policy_source:"human_subject_override",hold_status:"active" as const,active_hold_id:"cccccccc-cccc-4ccc-8ccc-cccccccccccc",active_hold_version:4,disposition_eligibility:"blocked_by_hold" as const,disposition_decision:"none" as const,version:2,predecessor_record_id:null,record_digest:"a".repeat(64)};

beforeEach(()=>{for(const fn of Object.values(apiMock))fn.mockReset();for(const fn of Object.values(retentionMock))fn.mockReset();apiMock.evidence.mockResolvedValue({state:"success",data:{items:[evidence]}});retentionMock.state.mockResolvedValue({state:"success",data:state});retentionMock.workbench.mockResolvedValue({state:"success",data:{project_id:7,workspace_id:9,evidence:[{evidence_id:evidence.id,lifecycle:"current",source_standing:"current",supported_fact:evidence.supported_fact,version:3,replacement_evidence_id:null,predecessor_evidence_ids:[],reliance:[],retention_state:state}],supporting_files:[],visible_count:1}});});

it("P055-UX-01 ordinary journey uses selections and no raw UUID fields",async()=>{render(<EvidenceWorkbench projectId={7} workspaceId={9}/>);expect(await screen.findAllByText("Verified relay setting basis")).not.toHaveLength(0);expect(screen.queryByLabelText(/uuid|organization id|project id|workspace id/i)).not.toBeInTheDocument();});
it("P055-UX-02 distinguishes scanner, Evidence, historical reliance and disposition states",async()=>{render(<EvidenceWorkbench projectId={7} workspaceId={9}/>);expect(await screen.findByText(/Scanner availability, Evidence currentness, historical reliance and retention eligibility are separate governed states/i)).toBeVisible();expect(screen.getByText(/Current engineering Evidence/i)).toBeVisible();});
it("P055-UX-03 conflict forces authoritative reread before another decision",async()=>{retentionMock.release.mockResolvedValue({state:"conflict"});const user=userEvent.setup();render(<RetentionGovernancePanel evidence={[evidence]} projectId={7} workspaceId={9}/>);await user.selectOptions(screen.getByLabelText("Evidence"),evidence.id);await waitFor(()=>expect(retentionMock.state).toHaveBeenCalled());await user.type(screen.getByLabelText("Human governance rationale"),"Human review");const release=screen.getByRole("button",{name:"Release Human hold"});await user.click(release);await waitFor(()=>expect(retentionMock.release).toHaveBeenCalledWith(expect.anything(),state.active_hold_id,{release_rationale:"Human review",expected_version:4}));await waitFor(()=>expect(retentionMock.state.mock.calls.length).toBeGreaterThanOrEqual(2));});
it("P055-UX-04 preserves semantic controls, live regions, focus support and RTL context",async()=>{const view=render(<div dir="rtl"><EvidenceWorkbench projectId={7} workspaceId={9}/></div>);expect(await screen.findByRole("heading",{name:"Evidence Workbench"})).toBeVisible();expect(view.container.querySelector("[dir='rtl']")).not.toBeNull();expect(screen.getAllByRole("status").length).toBeGreaterThan(0);expect(screen.getAllByRole("button").length).toBeGreaterThan(0);});
it("P055-UX-05 exposes legacy retention as not established without fabricated decision",async()=>{retentionMock.state.mockResolvedValue({state:"success",data:{...state,retention_record_id:null,retention_mode:null,hold_status:null,active_hold_id:null,active_hold_version:null,disposition_eligibility:"indeterminate",disposition_decision:"none",version:null,record_digest:null}});render(<RetentionGovernancePanel evidence={[evidence]} projectId={7} workspaceId={9}/>);await userEvent.setup().selectOptions(screen.getByLabelText("Evidence"),evidence.id);expect(await screen.findByText("not established")).toBeVisible();expect(screen.getByText(/Human disposition: none/i)).toBeVisible();});
it("P055-UX-06 keeps migration truth outside UI authority and freezes exactly six UX vectors",()=>{expect(new Set(PATCH055_FRONTEND_VECTORS).size).toBe(6);expect(PATCH055_FRONTEND_VECTORS).toEqual(Array.from({length:6},(_,i)=>`P055-UX-0${i+1}`));expect(document.querySelector("[data-fabricated-retention-decision]")).toBeNull();});
