import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { MemoryPage } from "../pages/KnowledgePages";

const { apiMock } = vi.hoisted(() => ({ apiMock: { projects: vi.fn(), workspaces: vi.fn(), memory: vi.fn(), memoryDetail: vi.fn() } }));
vi.mock("../api/client", () => ({ api: apiMock }));
const memoryId = "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee"; const reportId = "bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb";
const summary = { memory_id: memoryId, version: 1, standing: "active", source_report_id: reportId, source_accepted_version: 2, purpose: "engineering_analysis", organization_id: "7e7c9d7a-7693-4f75-9bc5-3ef7bf528281", workspace_id: 9, project_id: 7, admitted_by_id: 11, admitted_at: "2026-08-20T10:00:00Z", updated_at: "2026-08-20T10:00:00Z" };
const projection = { projection_contract: "organizational_memory.accepted_report.v1", report_id: reportId, purpose: "engineering_analysis", organization_id: summary.organization_id, workspace_id: 9, project_id: 7, content: { engineering_scope: "Relay panel", technical_content: "Verified terminal torque.", assumptions: [], uncertainty: "None material.", limitations: ["Applies to panel X1 only."], conclusions: "Retorque resolved the issue.", recommendations: [] }, qualification: { is_preliminary: false, evidence_deficiencies: [], unresolved_issues: [], follow_up_requirements: [] }, accepted_draft_revision_id: "cccccccc-cccc-4ccc-8ccc-cccccccccccc", accepted_draft_revision_number: 1, accepted_aggregate_version: 2, accepted_by_id: 11, accepted_at: summary.admitted_at, predecessor_report_id: null };

beforeEach(() => { for (const fn of Object.values(apiMock)) fn.mockReset(); apiMock.projects.mockResolvedValue({ state: "success", data: { items: [{ id: 7, project_code: "SAT-007", name: "Substation" }] } }); apiMock.workspaces.mockResolvedValue({ state: "success", data: { items: [{ id: 9, display_name: "Electrical Engineering" }], total: 1 } }); });

it("discovers active Memory through authorized selectors and deep-links exact detail", async () => { apiMock.memory.mockResolvedValue({ state: "success", data: { outcome: "success", page: { items: [summary], visible_total: 1, next_continuation: null } } }); const user = userEvent.setup(); render(<MemoryRouter><MemoryPage /></MemoryRouter>); await user.selectOptions(await screen.findByLabelText("Project"), "7"); await user.selectOptions(await screen.findByLabelText("Engineering Workspace"), "9"); expect(await screen.findByRole("link", { name: /Governed Memory/i })).toHaveAttribute("href", expect.stringContaining(`/memory/${memoryId}`)); expect(screen.queryByLabelText(/Project ID|Workspace ID/i)).not.toBeInTheDocument(); });

it("reauthorizes source and provenance for deliberate Human consultation", async () => { apiMock.memoryDetail.mockResolvedValue({ state: "success", data: { outcome: "success", item: { summary, projection, admission_rationale: "Preserve verified finding", reuse_restrictions: ["Confirm equipment applicability"], safe_provenance: [{ entry_id: "dddddddd-dddd-4ddd-8ddd-dddddddddddd", ordinal: 0, source_class: "canonical_material", source_type: "universal_capture", owning_capability: "universal_capture", is_material: true, reliance_role: "source_capture", locator_digest: "a".repeat(64), source_integrity_algorithm: "sha256", source_integrity_digest: "b".repeat(64) }] } } }); render(<MemoryRouter initialEntries={[`/memory/${memoryId}`]}><Routes><Route path="/memory/:memoryId" element={<MemoryPage />} /></Routes></MemoryRouter>); expect(await screen.findByText("Verified terminal torque.")).toBeVisible(); expect(screen.getByText("Confirm equipment applicability")).toBeVisible(); expect(screen.getByText(/Responsible Human consultation/)).toBeVisible(); expect(screen.getByRole("link", { name: "Open exact Technical Report" })).toHaveAttribute("href", expect.stringContaining(reportId)); await waitFor(() => expect(apiMock.memoryDetail).toHaveBeenCalledWith(memoryId)); });

it("collapses revoked or foreign Memory detail to a payload-free protected state", async () => { apiMock.memoryDetail.mockResolvedValue({ state: "protected" }); render(<MemoryRouter initialEntries={[`/memory/${memoryId}`]}><Routes><Route path="/memory/:memoryId" element={<MemoryPage />} /></Routes></MemoryRouter>); expect(await screen.findByText("Not available")).toBeVisible(); expect(screen.queryByText(memoryId)).not.toBeInTheDocument(); expect(screen.queryByText(reportId)).not.toBeInTheDocument(); });
