import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { ProjectEngineeringContextPanel } from "../components/ProjectEngineeringContextPanel";

const {apiMock}=vi.hoisted(()=>({apiMock:{projectContext:vi.fn(),relatedContext:vi.fn()}}));
vi.mock("../api/client",()=>({api:apiMock}));

const provenance={owner_kind:"project",selector:"7",version:4,standing:"active",source_observed_at:null,observed_at:"2026-08-26T00:00:00Z",authority_class:"human_authoritative",temporal_class:"current"};
const kinds=["project_basis","execution","deliverables","project_controls","engineering_context","engineering_objects","evidence","supporting_files","technical_reports","organizational_memory"] as const;
const context={status:"success",observation_started_at:"2026-08-26T00:00:00Z",observation_completed_at:"2026-08-26T00:00:01Z",observation_status:"partial",sections:kinds.map((kind,index)=>index===0?{kind,state:{state:"available",visible_count:1,truncated:{truncated:true,continuation:{continuation:"opaque-token",last_evaluated_key:"safe-anchor"}},observed_at:"2026-08-26T00:00:01Z"},items:[{item_kind:"project_basis",selector:"7",version:4,standing:"active",project_id:7,project_name:"Protection renewal",provenance}]}:{kind,state:{state:index===1?"not_established":index===2?"not_disclosed":index===3?"unavailable":"empty"},items:[]})};

beforeEach(()=>{apiMock.projectContext.mockReset();apiMock.relatedContext.mockReset();apiMock.projectContext.mockResolvedValue({state:"success",data:context});apiMock.relatedContext.mockResolvedValue({state:"success",data:{status:"success",start:{node_kind:"project",selector:7,navigation:{project_id:7,workspace_id:null},provenance,authority_class:"human_authoritative",temporal_class:"current"},edges:[],nodes:[],truncated:{truncated:false,continuation:null}}});});

it("renders ten canonical real-data sections and truthful partial states",async()=>{render(<ProjectEngineeringContextPanel projectId={7} workspaceId={9}/>);expect(await screen.findByText("Protection renewal")).toBeVisible();for(const label of ["Project basis","Execution","Deliverables","Project controls","Engineering context","Engineering objects","Evidence","Supporting files","Technical reports","Organizational memory"])expect(screen.getAllByText(label).length).toBeGreaterThan(0);expect(screen.getByText(/Observation partial/)).toBeVisible();expect(screen.getByText("Not established")).toBeVisible();expect(screen.getAllByText("Not available").length).toBeGreaterThan(0);expect(screen.queryByText(/total|complete context|sample|demo record/i)).not.toBeInTheDocument();});

it("uses keyboard-operable server continuation and rendered selectors only",async()=>{const user=userEvent.setup();render(<ProjectEngineeringContextPanel projectId={7} workspaceId={9}/>);await screen.findByText("Protection renewal");apiMock.projectContext.mockResolvedValueOnce({state:"success",data:{...context,sections:[{kind:"project_basis",state:{state:"empty"},items:[]}]}});await user.click(screen.getByRole("button",{name:"Load next bounded page"}));expect(apiMock.projectContext).toHaveBeenLastCalledWith(7,9,"project_basis","opaque-token");await user.click(screen.getByRole("button",{name:/Related context/i}));expect(apiMock.relatedContext).toHaveBeenCalledWith(7,"project",7,9);expect(screen.queryByRole("textbox")).not.toBeInTheDocument();});

it("uses each rendered canonical owner selector rather than the Project id",async()=>{apiMock.projectContext.mockResolvedValue({state:"success",data:{...context,sections:[{kind:"deliverables",state:{state:"available",visible_count:1,truncated:{truncated:false,continuation:null},observed_at:"2026-08-26T00:00:01Z"},items:[{item_kind:"deliverable",selector:"d",version:1,standing:"active",project_id:7,deliverable_id:"00000000-0000-4000-8000-000000000048",title:"Protection study",provenance}]}]}});const user=userEvent.setup();render(<ProjectEngineeringContextPanel projectId={7}/>);await user.click(await screen.findByRole("button",{name:/Related context/i}));expect(apiMock.relatedContext).toHaveBeenCalledWith(7,"deliverable","00000000-0000-4000-8000-000000000048",undefined);});

it("collapses protected context without identities or denial detail",async()=>{apiMock.projectContext.mockResolvedValue({state:"protected"});render(<ProjectEngineeringContextPanel projectId={7}/>);expect(await screen.findByText("Not available")).toBeVisible();expect(screen.queryByText(/Protection renewal|forbidden|denied|organization/i)).not.toBeInTheDocument();});
