import { render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { ProjectControlsPanel } from "../components/ProjectControlsPanel";

const { apiMock } = vi.hoisted(() => ({ apiMock: { projectControls:vi.fn(), projectControlHistory:vi.fn(), createProjectControl:vi.fn(), transitionProjectControl:vi.fn(), createChangeImpact:vi.fn(), confirmChangeImpact:vi.fn(), executionPlan:vi.fn(), deliverables:vi.fn(), evidence:vi.fn(), supportingFiles:vi.fn() } }));
vi.mock("../api/client", () => ({ api:apiMock }));
const workspace={id:3,project_id:7,project_code:"SAT-007",project_name:"Protection renewal",discipline:"electrical",display_name:"Electrical Engineering",description:null,status:"active",version:1,updated_at:"2026-08-24T00:00:00Z",allowed_actions:[]};
const change={outcome:"success",id:"10000000-0000-0000-0000-000000000001",version:1,organization_id:"04700000-0000-4000-8000-000000000001",project_id:7,workspace_id:3,standing:"recorded",statement:"Cable route changed",rationale:"Human observed changed route",predecessor_id:null,owner_id:null,disposition:null,observed_context:null,alternatives:[],accepted_by_id:null,accepted_at:null,confirmed_by_id:null,confirmed_at:null,impacts:[{id:"20000000-0000-0000-0000-000000000001",change_id:"10000000-0000-0000-0000-000000000001",target_kind:"activity",target_id:"30000000-0000-0000-0000-000000000001",statement:"Termination work may be affected",standing:"potential",confirmed_by_id:null,confirmed_at:null}]} as const;
const issue={...change,id:"40000000-0000-0000-0000-000000000001",standing:"open",statement:"Loose terminal",observed_context:"Observed during inspection",impacts:[]} as const;
beforeEach(() => { for (const fn of Object.values(apiMock)) fn.mockReset(); apiMock.projectControls.mockImplementation((_id:number,kind:string) => Promise.resolve({state:"success",data:{outcome:"success",kind,items:kind==="change"?[change]:kind==="issue"?[issue]:[],visible_count:kind==="change"||kind==="issue"?1:0}})); apiMock.executionPlan.mockResolvedValue({state:"success",data:{outcome:"success",availability:"established",project_id:7,plan_id:"50000000-0000-0000-0000-000000000001",version:1,activities:[{id:"30000000-0000-0000-0000-000000000001",title:"Termination work",workspace_id:3}],milestones:[],dependencies:[],progress:{completed_count:0,eligible_count:0,percent:0}}}); apiMock.deliverables.mockResolvedValue({state:"success",data:{outcome:"success",items:[],visible_count:0,continuation:null}}); apiMock.evidence.mockResolvedValue({state:"success",data:{items:[]}}); apiMock.supportingFiles.mockResolvedValue({state:"success",data:{items:[]}}); apiMock.createProjectControl.mockResolvedValue({state:"success",data:{outcome:"success",id:"60000000-0000-0000-0000-000000000001",version:1}}); apiMock.transitionProjectControl.mockResolvedValue({state:"success",data:{outcome:"success",id:change.id,version:2}}); apiMock.confirmChangeImpact.mockResolvedValue({state:"success",data:{outcome:"success",id:change.impacts[0].id,change_id:change.id,standing:"confirmed"}}); });

it("renders truthful Risk/Issue/Decision/Change distinctions without raw target identity entry", async () => { render(<ProjectControlsPanel projectId={7} workspaces={[workspace]} />); expect(await screen.findByText(/Uncertain future engineering impact/i)).toBeVisible(); await userEvent.setup().click(screen.getByRole("tab",{name:"Issues"})); expect(await screen.findByText("Observed during inspection")).toBeVisible(); expect(screen.getByText(/never an Activity blocker/i)).toBeVisible(); expect(screen.queryByLabelText(/target id|organization id|project id/i)).not.toBeInTheDocument(); });

it("records a Human-authored Risk and keeps protected results neutral", async () => { const user=userEvent.setup(); render(<ProjectControlsPanel projectId={7} workspaces={[workspace]} />); await user.type(await screen.findByLabelText("Engineering statement"),"Relay availability risk"); await user.type(screen.getByLabelText("Human rationale"),"Human records uncertain future impact"); await user.click(screen.getByRole("button",{name:/Record risk/i})); expect(apiMock.createProjectControl).toHaveBeenCalledWith(7,"risk",expect.objectContaining({statement:"Relay availability risk",rationale:"Human records uncertain future impact"})); apiMock.projectControls.mockResolvedValueOnce({state:"protected"}); render(<ProjectControlsPanel projectId={8} workspaces={[]}/>); expect(await screen.findByText("Not available")).toBeVisible(); expect(screen.queryByText(/Relay availability risk/i)).not.toBeInTheDocument(); });

it("makes potential Impact distinct from explicit Human confirmation", async () => { const user=userEvent.setup(); render(<ProjectControlsPanel projectId={7} workspaces={[workspace]} />); await user.click(await screen.findByRole("tab",{name:"Changes"})); expect(await screen.findByText(/Potential impact is not confirmed engineering truth/i)).toBeVisible(); const rationale=screen.getByLabelText("Human confirmation rationale"); expect(screen.getByRole("button",{name:/Human confirm impact/i})).toBeDisabled(); await user.type(rationale,"Human confirms the assessed Change Impact"); await user.click(screen.getByRole("button",{name:/Human confirm impact/i})); expect(apiMock.confirmChangeImpact).toHaveBeenCalledWith(7,change.impacts[0].id,expect.objectContaining({expected_change_version:1,rationale:"Human confirms the assessed Change Impact"})); expect(screen.queryByText(/AI confirmed|risk score|ticket board/i)).not.toBeInTheDocument(); });

it("requires an explicit Human rationale for a Change lifecycle action", async () => { const user=userEvent.setup(); render(<ProjectControlsPanel projectId={7} workspaces={[workspace]} />); await user.click(await screen.findByRole("tab",{name:"Changes"})); const select=await screen.findByLabelText(`Human lifecycle action for ${change.statement}`); await user.selectOptions(select,"confirmed"); const rationale=screen.getByLabelText(`Human transition rationale for ${change.statement}`); expect(screen.getByRole("button",{name:"Record Human transition"})).toBeDisabled(); await user.type(rationale,"Human confirms the changed route"); await user.click(screen.getByRole("button",{name:"Record Human transition"})); expect(apiMock.transitionProjectControl).toHaveBeenCalledWith(7,"change",change.id,{target_standing:"confirmed",expected_version:1,rationale:"Human confirms the changed route"}); });

it("uses semantic controls and accessible history presentation", async () => { apiMock.projectControlHistory.mockResolvedValue({state:"success",data:{outcome:"success",kind:"issue",control_id:issue.id,items:[{id:"70000000-0000-0000-0000-000000000001",aggregate_version:1,event_type:"create_issue",actor_id:7,occurred_at:"2026-08-24T00:00:00Z"}],visible_count:1}}); const user=userEvent.setup(); render(<ProjectControlsPanel projectId={7} workspaces={[workspace]} />); await user.click(screen.getByRole("tab",{name:"Issues"})); await user.click(await screen.findByRole("button",{name:"History"})); expect(await screen.findByText("Immutable control history")).toBeVisible(); expect(screen.getByRole("tablist",{name:"Project control records"})).toBeVisible(); });
