"""Evidence Foundation.

Revision ID: e02700000001
Revises: e02500000001
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="e02700000001"; down_revision="e02500000001"; branch_labels=None; depends_on=None
LIFECYCLE="'proposed','current','withdrawn','superseded','rejected'"
KIND="'engineering_record','external_reference','human_review','technical_decision','standard_reference','inspection_record','commissioning_record'"
STANDING="'draft','current','withdrawn','superseded'"
def upgrade():
    op.create_table("evidence",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("organization_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("organizations.id",ondelete="RESTRICT"),nullable=False),sa.Column("project_id",sa.Integer(),sa.ForeignKey("projects.id",ondelete="RESTRICT")),sa.Column("workspace_id",sa.Integer(),sa.ForeignKey("engineering_workspaces.id",ondelete="RESTRICT")),sa.Column("lifecycle",sa.String(16),server_default="proposed",nullable=False),sa.Column("source_kind",sa.String(32),nullable=False),sa.Column("source_reference",sa.String(512),nullable=False),sa.Column("source_revision",sa.String(128),nullable=False),sa.Column("source_standing",sa.String(16),nullable=False),sa.Column("effective_at",sa.DateTime(timezone=True)),sa.Column("supported_fact",sa.String(2000),nullable=False),sa.Column("creator_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("version",sa.Integer(),server_default="1",nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.CheckConstraint(f"lifecycle IN ({LIFECYCLE})",name="ck_evidence_lifecycle"),sa.CheckConstraint(f"source_kind IN ({KIND})",name="ck_evidence_source_kind"),sa.CheckConstraint(f"source_standing IN ({STANDING})",name="ck_evidence_source_standing"),sa.CheckConstraint("workspace_id IS NULL OR project_id IS NOT NULL",name="ck_evidence_workspace_project"),sa.CheckConstraint("version>=1",name="ck_evidence_version"))
    op.create_index("ix_evidence_scope","evidence",["organization_id","project_id","workspace_id","lifecycle"])
    op.create_table("evidence_outbox",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("event_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("aggregate_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("evidence.id",ondelete="RESTRICT"),nullable=False),sa.Column("aggregate_version",sa.Integer(),nullable=False),sa.Column("event_type",sa.String(96),nullable=False),sa.Column("payload",sa.JSON(),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("published_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("event_id",name="uq_evidence_outbox_event"),sa.CheckConstraint("aggregate_version>=1",name="ck_evidence_outbox_version"))
    op.create_table("evidence_idempotency",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("actor_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("command_type",sa.String(64),nullable=False),sa.Column("idempotency_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("request_fingerprint",sa.String(64),nullable=False),sa.Column("status",sa.String(16),server_default="pending",nullable=False),sa.Column("aggregate_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("evidence.id",ondelete="RESTRICT")),sa.Column("result",sa.JSON()),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("actor_id","command_type","idempotency_id",name="uq_evidence_idempotency_scope"),sa.CheckConstraint("status IN ('pending','completed')",name="ck_evidence_idempotency_status"))
def downgrade():
    op.drop_table("evidence_idempotency"); op.drop_table("evidence_outbox"); op.drop_index("ix_evidence_scope",table_name="evidence"); op.drop_table("evidence")
