"""Engineering Deliverable Register and external-tool document control.

Revision ID: e04600000001
Revises: e04500000001
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision="e04600000001"; down_revision="e04500000001"; branch_labels=None; depends_on=None

def upgrade():
    op.create_table("engineering_deliverables",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("organization_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("organizations.id",ondelete="RESTRICT"),nullable=False),sa.Column("project_id",sa.Integer(),sa.ForeignKey("projects.id",ondelete="RESTRICT"),nullable=False),sa.Column("workspace_id",sa.Integer(),sa.ForeignKey("engineering_workspaces.id",ondelete="RESTRICT")),sa.Column("activity_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("engineering_execution_activities.id",ondelete="RESTRICT")),sa.Column("milestone_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("engineering_execution_milestones.id",ondelete="RESTRICT")),sa.Column("code",sa.String(64),nullable=False),sa.Column("title",sa.String(200),nullable=False),sa.Column("discipline",sa.String(80),nullable=False),sa.Column("deliverable_type",sa.String(80),nullable=False),sa.Column("purpose",sa.String(2000)),sa.Column("external_authority",sa.String(32),nullable=False),sa.Column("responsible_user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="RESTRICT")),sa.Column("target_date",sa.Date()),sa.Column("standing",sa.String(32),nullable=False,server_default="planned"),sa.Column("current_revision_sequence",sa.Integer(),nullable=False,server_default="1"),sa.Column("version",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_by_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_by_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("length(btrim(code)) BETWEEN 1 AND 64",name="ck_deliverable_code"),sa.CheckConstraint("length(btrim(title)) BETWEEN 1 AND 200",name="ck_deliverable_title"),sa.CheckConstraint("length(btrim(discipline)) BETWEEN 1 AND 80",name="ck_deliverable_discipline"),sa.CheckConstraint("length(btrim(deliverable_type)) BETWEEN 1 AND 80",name="ck_deliverable_type"),sa.CheckConstraint("standing IN ('planned','in_preparation','ready_for_review','reviewed','issued','withdrawn','cancelled')",name="ck_deliverable_standing"),sa.CheckConstraint("external_authority IN ('cad','eplan','etap','spreadsheet','document','vendor_tool','other')",name="ck_deliverable_external_authority"),sa.CheckConstraint("version>=1 AND current_revision_sequence>=1",name="ck_deliverable_versions"),sa.UniqueConstraint("project_id","code",name="uq_deliverable_project_code"))
    op.create_index("ix_deliverable_project_order","engineering_deliverables",["organization_id","project_id","target_date","code","id"])
    op.create_table("engineering_deliverable_revisions",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("deliverable_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("engineering_deliverables.id",ondelete="RESTRICT"),nullable=False),sa.Column("organization_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("organizations.id",ondelete="RESTRICT"),nullable=False),sa.Column("project_id",sa.Integer(),sa.ForeignKey("projects.id",ondelete="RESTRICT"),nullable=False),sa.Column("sequence",sa.Integer(),nullable=False),sa.Column("external_label",sa.String(80),nullable=False),sa.Column("source_reference",sa.String(512)),sa.Column("supporting_file_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("supporting_file_assets.id",ondelete="RESTRICT")),sa.Column("standing",sa.String(32),nullable=False,server_default="draft"),sa.Column("version",sa.Integer(),nullable=False,server_default="1"),sa.Column("rationale",sa.String(2000),nullable=False),sa.Column("created_by_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("transitioned_by_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("transitioned_at",sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("sequence>=1 AND version>=1",name="ck_deliverable_revision_versions"),sa.CheckConstraint("standing IN ('draft','ready_for_review','reviewed','issued','superseded','withdrawn')",name="ck_deliverable_revision_standing"),sa.UniqueConstraint("deliverable_id","sequence",name="uq_deliverable_revision_sequence"))
    op.create_index("ix_deliverable_revision_history","engineering_deliverable_revisions",["organization_id","deliverable_id","sequence"])
    op.create_table("engineering_deliverable_history",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("deliverable_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("engineering_deliverables.id",ondelete="RESTRICT"),nullable=False),sa.Column("organization_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("organizations.id",ondelete="RESTRICT"),nullable=False),sa.Column("aggregate_version",sa.Integer(),nullable=False),sa.Column("event_type",sa.String(80),nullable=False),sa.Column("revision_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("engineering_deliverable_revisions.id",ondelete="RESTRICT")),sa.Column("actor_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("deliverable_id","aggregate_version",name="uq_deliverable_history_version"))
    op.create_table("engineering_deliverable_idempotency",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("organization_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("organizations.id",ondelete="RESTRICT"),nullable=False),sa.Column("actor_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="RESTRICT"),nullable=False),sa.Column("operation",sa.String(32),nullable=False),sa.Column("idempotency_key",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("fingerprint",sa.String(64),nullable=False),sa.Column("replay_json",postgresql.JSONB(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("length(fingerprint)=64",name="ck_deliverable_idempotency_fingerprint"),sa.CheckConstraint("length(replay_json::text)<=1024",name="ck_deliverable_idempotency_size"),sa.UniqueConstraint("organization_id","actor_id","operation","idempotency_key",name="uq_deliverable_idempotency_key"))
    op.create_table("engineering_deliverable_outbox",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("event_id",postgresql.UUID(as_uuid=True),nullable=False,unique=True),sa.Column("deliverable_id",postgresql.UUID(as_uuid=True),sa.ForeignKey("engineering_deliverables.id",ondelete="RESTRICT"),nullable=False),sa.Column("aggregate_version",sa.Integer(),nullable=False),sa.Column("event_type",sa.String(96),nullable=False),sa.Column("payload",postgresql.JSONB(),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False))
    op.execute("""CREATE FUNCTION satco_deliverable_guard() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE project_org uuid; BEGIN SELECT organization_id INTO project_org FROM projects WHERE id=NEW.project_id FOR SHARE; IF project_org IS NULL OR NEW.organization_id IS DISTINCT FROM project_org THEN RAISE EXCEPTION 'deliverable project scope mismatch'; END IF; IF NEW.workspace_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM engineering_workspaces w WHERE w.id=NEW.workspace_id AND w.project_id=NEW.project_id) THEN RAISE EXCEPTION 'deliverable workspace mismatch'; END IF; IF TG_OP='UPDATE' AND (NEW.organization_id IS DISTINCT FROM OLD.organization_id OR NEW.project_id IS DISTINCT FROM OLD.project_id OR NEW.created_by_id IS DISTINCT FROM OLD.created_by_id OR NEW.created_at IS DISTINCT FROM OLD.created_at OR NEW.version<>OLD.version+1) THEN RAISE EXCEPTION 'deliverable immutable identity/version'; END IF; RETURN NEW; END $$; CREATE TRIGGER trg_deliverable_guard BEFORE INSERT OR UPDATE ON engineering_deliverables FOR EACH ROW EXECUTE FUNCTION satco_deliverable_guard(); CREATE FUNCTION satco_deliverable_revision_guard() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE root engineering_deliverables%ROWTYPE; BEGIN IF TG_OP<>'INSERT' AND OLD.standing IN ('superseded','withdrawn') THEN RAISE EXCEPTION 'terminal revision immutable'; END IF; SELECT * INTO root FROM engineering_deliverables WHERE id=NEW.deliverable_id FOR SHARE; IF root.id IS NULL OR root.organization_id IS DISTINCT FROM NEW.organization_id OR root.project_id IS DISTINCT FROM NEW.project_id THEN RAISE EXCEPTION 'revision scope mismatch'; END IF; IF NEW.sequence>root.current_revision_sequence THEN RAISE EXCEPTION 'revision sequence invalid'; END IF; RETURN NEW; END $$; CREATE TRIGGER trg_deliverable_revision_guard BEFORE INSERT OR UPDATE OR DELETE ON engineering_deliverable_revisions FOR EACH ROW EXECUTE FUNCTION satco_deliverable_revision_guard(); REVOKE ALL ON TABLE engineering_deliverables, engineering_deliverable_revisions, engineering_deliverable_history, engineering_deliverable_idempotency, engineering_deliverable_outbox FROM satco_runtime; GRANT SELECT, INSERT, UPDATE ON engineering_deliverables, engineering_deliverable_revisions, engineering_deliverable_idempotency TO satco_runtime; GRANT SELECT, INSERT ON engineering_deliverable_history, engineering_deliverable_outbox TO satco_runtime; GRANT EXECUTE ON FUNCTION satco_deliverable_guard(), satco_deliverable_revision_guard() TO satco_runtime;""")
def downgrade():
    op.execute("DROP FUNCTION IF EXISTS satco_deliverable_revision_guard() CASCADE; DROP FUNCTION IF EXISTS satco_deliverable_guard() CASCADE")
    op.drop_table("engineering_deliverable_outbox");op.drop_table("engineering_deliverable_idempotency");op.drop_table("engineering_deliverable_history");op.drop_index("ix_deliverable_revision_history",table_name="engineering_deliverable_revisions");op.drop_table("engineering_deliverable_revisions");op.drop_index("ix_deliverable_project_order",table_name="engineering_deliverables");op.drop_table("engineering_deliverables")
